// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

public interface AttachmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Attachment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *oneof Type {
   * </pre>
   *
   * <code>optional .HtmlAttachment html = 1;</code>
   * @return Whether the html field is set.
   */
  boolean hasHtml();
  /**
   * <pre>
   *oneof Type {
   * </pre>
   *
   * <code>optional .HtmlAttachment html = 1;</code>
   * @return The html.
   */
  org.matrix.dma.gchat.proto.HtmlAttachment getHtml();
  /**
   * <pre>
   *oneof Type {
   * </pre>
   *
   * <code>optional .HtmlAttachment html = 1;</code>
   */
  org.matrix.dma.gchat.proto.HtmlAttachmentOrBuilder getHtmlOrBuilder();

  /**
   * <code>optional .JAddOnsContextualAddOn add_on_data = 2;</code>
   * @return Whether the addOnData field is set.
   */
  boolean hasAddOnData();
  /**
   * <code>optional .JAddOnsContextualAddOn add_on_data = 2;</code>
   * @return The addOnData.
   */
  org.matrix.dma.gchat.proto.JAddOnsContextualAddOn getAddOnData();
  /**
   * <code>optional .JAddOnsContextualAddOn add_on_data = 2;</code>
   */
  org.matrix.dma.gchat.proto.JAddOnsContextualAddOnOrBuilder getAddOnDataOrBuilder();

  /**
   * <pre>
   *}
   * </pre>
   *
   * <code>optional .UserId app_id = 5;</code>
   * @return Whether the appId field is set.
   */
  boolean hasAppId();
  /**
   * <pre>
   *}
   * </pre>
   *
   * <code>optional .UserId app_id = 5;</code>
   * @return The appId.
   */
  org.matrix.dma.gchat.proto.UserId getAppId();
  /**
   * <pre>
   *}
   * </pre>
   *
   * <code>optional .UserId app_id = 5;</code>
   */
  org.matrix.dma.gchat.proto.UserIdOrBuilder getAppIdOrBuilder();

  /**
   * <code>optional .User app_user = 6;</code>
   * @return Whether the appUser field is set.
   */
  boolean hasAppUser();
  /**
   * <code>optional .User app_user = 6;</code>
   * @return The appUser.
   */
  org.matrix.dma.gchat.proto.User getAppUser();
  /**
   * <code>optional .User app_user = 6;</code>
   */
  org.matrix.dma.gchat.proto.UserOrBuilder getAppUserOrBuilder();
}
