// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code CustomStatus}
 */
public final class CustomStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CustomStatus)
    CustomStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomStatus.newBuilder() to construct.
  private CustomStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomStatus() {
    statusText_ = "";
    statusEmoji_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CustomStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_CustomStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_CustomStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.CustomStatus.class, org.matrix.dma.gchat.proto.CustomStatus.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_TEXT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statusText_ = "";
  /**
   * <code>optional string status_text = 1;</code>
   * @return Whether the statusText field is set.
   */
  @java.lang.Override
  public boolean hasStatusText() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string status_text = 1;</code>
   * @return The statusText.
   */
  @java.lang.Override
  public java.lang.String getStatusText() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        statusText_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status_text = 1;</code>
   * @return The bytes for statusText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusTextBytes() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_EMOJI_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statusEmoji_ = "";
  /**
   * <code>optional string status_emoji = 2;</code>
   * @return Whether the statusEmoji field is set.
   */
  @java.lang.Override
  public boolean hasStatusEmoji() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string status_emoji = 2;</code>
   * @return The statusEmoji.
   */
  @java.lang.Override
  public java.lang.String getStatusEmoji() {
    java.lang.Object ref = statusEmoji_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        statusEmoji_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string status_emoji = 2;</code>
   * @return The bytes for statusEmoji.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusEmojiBytes() {
    java.lang.Object ref = statusEmoji_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusEmoji_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_EXPIRY_TIMESTAMP_USEC_FIELD_NUMBER = 3;
  private long stateExpiryTimestampUsec_ = 0L;
  /**
   * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
   * @return Whether the stateExpiryTimestampUsec field is set.
   */
  @java.lang.Override
  public boolean hasStateExpiryTimestampUsec() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
   * @return The stateExpiryTimestampUsec.
   */
  @java.lang.Override
  public long getStateExpiryTimestampUsec() {
    return stateExpiryTimestampUsec_;
  }

  public static final int EMOJI_FIELD_NUMBER = 4;
  private org.matrix.dma.gchat.proto.Emoji emoji_;
  /**
   * <code>optional .Emoji emoji = 4;</code>
   * @return Whether the emoji field is set.
   */
  @java.lang.Override
  public boolean hasEmoji() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .Emoji emoji = 4;</code>
   * @return The emoji.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Emoji getEmoji() {
    return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
  }
  /**
   * <code>optional .Emoji emoji = 4;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.EmojiOrBuilder getEmojiOrBuilder() {
    return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statusText_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statusEmoji_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(3, stateExpiryTimestampUsec_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getEmoji());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statusText_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statusEmoji_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, stateExpiryTimestampUsec_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEmoji());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.CustomStatus)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.CustomStatus other = (org.matrix.dma.gchat.proto.CustomStatus) obj;

    if (hasStatusText() != other.hasStatusText()) return false;
    if (hasStatusText()) {
      if (!getStatusText()
          .equals(other.getStatusText())) return false;
    }
    if (hasStatusEmoji() != other.hasStatusEmoji()) return false;
    if (hasStatusEmoji()) {
      if (!getStatusEmoji()
          .equals(other.getStatusEmoji())) return false;
    }
    if (hasStateExpiryTimestampUsec() != other.hasStateExpiryTimestampUsec()) return false;
    if (hasStateExpiryTimestampUsec()) {
      if (getStateExpiryTimestampUsec()
          != other.getStateExpiryTimestampUsec()) return false;
    }
    if (hasEmoji() != other.hasEmoji()) return false;
    if (hasEmoji()) {
      if (!getEmoji()
          .equals(other.getEmoji())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatusText()) {
      hash = (37 * hash) + STATUS_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getStatusText().hashCode();
    }
    if (hasStatusEmoji()) {
      hash = (37 * hash) + STATUS_EMOJI_FIELD_NUMBER;
      hash = (53 * hash) + getStatusEmoji().hashCode();
    }
    if (hasStateExpiryTimestampUsec()) {
      hash = (37 * hash) + STATE_EXPIRY_TIMESTAMP_USEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStateExpiryTimestampUsec());
    }
    if (hasEmoji()) {
      hash = (37 * hash) + EMOJI_FIELD_NUMBER;
      hash = (53 * hash) + getEmoji().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.CustomStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.CustomStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CustomStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CustomStatus)
      org.matrix.dma.gchat.proto.CustomStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_CustomStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_CustomStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.CustomStatus.class, org.matrix.dma.gchat.proto.CustomStatus.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.CustomStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmojiFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      statusText_ = "";
      statusEmoji_ = "";
      stateExpiryTimestampUsec_ = 0L;
      emoji_ = null;
      if (emojiBuilder_ != null) {
        emojiBuilder_.dispose();
        emojiBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_CustomStatus_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.CustomStatus getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.CustomStatus.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.CustomStatus build() {
      org.matrix.dma.gchat.proto.CustomStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.CustomStatus buildPartial() {
      org.matrix.dma.gchat.proto.CustomStatus result = new org.matrix.dma.gchat.proto.CustomStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.CustomStatus result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.statusText_ = statusText_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.statusEmoji_ = statusEmoji_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stateExpiryTimestampUsec_ = stateExpiryTimestampUsec_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.emoji_ = emojiBuilder_ == null
            ? emoji_
            : emojiBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.CustomStatus) {
        return mergeFrom((org.matrix.dma.gchat.proto.CustomStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.CustomStatus other) {
      if (other == org.matrix.dma.gchat.proto.CustomStatus.getDefaultInstance()) return this;
      if (other.hasStatusText()) {
        statusText_ = other.statusText_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasStatusEmoji()) {
        statusEmoji_ = other.statusEmoji_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasStateExpiryTimestampUsec()) {
        setStateExpiryTimestampUsec(other.getStateExpiryTimestampUsec());
      }
      if (other.hasEmoji()) {
        mergeEmoji(other.getEmoji());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              statusText_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              statusEmoji_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              stateExpiryTimestampUsec_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getEmojiFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object statusText_ = "";
    /**
     * <code>optional string status_text = 1;</code>
     * @return Whether the statusText field is set.
     */
    public boolean hasStatusText() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string status_text = 1;</code>
     * @return The statusText.
     */
    public java.lang.String getStatusText() {
      java.lang.Object ref = statusText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statusText_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status_text = 1;</code>
     * @return The bytes for statusText.
     */
    public com.google.protobuf.ByteString
        getStatusTextBytes() {
      java.lang.Object ref = statusText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status_text = 1;</code>
     * @param value The statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statusText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status_text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusText() {
      statusText_ = getDefaultInstance().getStatusText();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string status_text = 1;</code>
     * @param value The bytes for statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      statusText_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object statusEmoji_ = "";
    /**
     * <code>optional string status_emoji = 2;</code>
     * @return Whether the statusEmoji field is set.
     */
    public boolean hasStatusEmoji() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string status_emoji = 2;</code>
     * @return The statusEmoji.
     */
    public java.lang.String getStatusEmoji() {
      java.lang.Object ref = statusEmoji_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statusEmoji_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status_emoji = 2;</code>
     * @return The bytes for statusEmoji.
     */
    public com.google.protobuf.ByteString
        getStatusEmojiBytes() {
      java.lang.Object ref = statusEmoji_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusEmoji_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status_emoji = 2;</code>
     * @param value The statusEmoji to set.
     * @return This builder for chaining.
     */
    public Builder setStatusEmoji(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statusEmoji_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status_emoji = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusEmoji() {
      statusEmoji_ = getDefaultInstance().getStatusEmoji();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string status_emoji = 2;</code>
     * @param value The bytes for statusEmoji to set.
     * @return This builder for chaining.
     */
    public Builder setStatusEmojiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      statusEmoji_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long stateExpiryTimestampUsec_ ;
    /**
     * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
     * @return Whether the stateExpiryTimestampUsec field is set.
     */
    @java.lang.Override
    public boolean hasStateExpiryTimestampUsec() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
     * @return The stateExpiryTimestampUsec.
     */
    @java.lang.Override
    public long getStateExpiryTimestampUsec() {
      return stateExpiryTimestampUsec_;
    }
    /**
     * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
     * @param value The stateExpiryTimestampUsec to set.
     * @return This builder for chaining.
     */
    public Builder setStateExpiryTimestampUsec(long value) {
      
      stateExpiryTimestampUsec_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 state_expiry_timestamp_usec = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStateExpiryTimestampUsec() {
      bitField0_ = (bitField0_ & ~0x00000004);
      stateExpiryTimestampUsec_ = 0L;
      onChanged();
      return this;
    }

    private org.matrix.dma.gchat.proto.Emoji emoji_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder> emojiBuilder_;
    /**
     * <code>optional .Emoji emoji = 4;</code>
     * @return Whether the emoji field is set.
     */
    public boolean hasEmoji() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     * @return The emoji.
     */
    public org.matrix.dma.gchat.proto.Emoji getEmoji() {
      if (emojiBuilder_ == null) {
        return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
      } else {
        return emojiBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public Builder setEmoji(org.matrix.dma.gchat.proto.Emoji value) {
      if (emojiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emoji_ = value;
      } else {
        emojiBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public Builder setEmoji(
        org.matrix.dma.gchat.proto.Emoji.Builder builderForValue) {
      if (emojiBuilder_ == null) {
        emoji_ = builderForValue.build();
      } else {
        emojiBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public Builder mergeEmoji(org.matrix.dma.gchat.proto.Emoji value) {
      if (emojiBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          emoji_ != null &&
          emoji_ != org.matrix.dma.gchat.proto.Emoji.getDefaultInstance()) {
          getEmojiBuilder().mergeFrom(value);
        } else {
          emoji_ = value;
        }
      } else {
        emojiBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public Builder clearEmoji() {
      bitField0_ = (bitField0_ & ~0x00000008);
      emoji_ = null;
      if (emojiBuilder_ != null) {
        emojiBuilder_.dispose();
        emojiBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public org.matrix.dma.gchat.proto.Emoji.Builder getEmojiBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEmojiFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    public org.matrix.dma.gchat.proto.EmojiOrBuilder getEmojiOrBuilder() {
      if (emojiBuilder_ != null) {
        return emojiBuilder_.getMessageOrBuilder();
      } else {
        return emoji_ == null ?
            org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
      }
    }
    /**
     * <code>optional .Emoji emoji = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder> 
        getEmojiFieldBuilder() {
      if (emojiBuilder_ == null) {
        emojiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder>(
                getEmoji(),
                getParentForChildren(),
                isClean());
        emoji_ = null;
      }
      return emojiBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CustomStatus)
  }

  // @@protoc_insertion_point(class_scope:CustomStatus)
  private static final org.matrix.dma.gchat.proto.CustomStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.CustomStatus();
  }

  public static org.matrix.dma.gchat.proto.CustomStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<CustomStatus>
      PARSER = new com.google.protobuf.AbstractParser<CustomStatus>() {
    @java.lang.Override
    public CustomStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CustomStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.CustomStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

