// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code GetGroupResponse}
 */
public final class GetGroupResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetGroupResponse)
    GetGroupResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetGroupResponse.newBuilder() to construct.
  private GetGroupResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetGroupResponse() {
    memberships_ = java.util.Collections.emptyList();
    membershipState_ = 0;
    joinedMemberIds_ = java.util.Collections.emptyList();
    invitedMemberIds_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetGroupResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_GetGroupResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_GetGroupResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.GetGroupResponse.class, org.matrix.dma.gchat.proto.GetGroupResponse.Builder.class);
  }

  private int bitField0_;
  public static final int GROUP_FIELD_NUMBER = 1;
  private org.matrix.dma.gchat.proto.Group group_;
  /**
   * <code>optional .Group group = 1;</code>
   * @return Whether the group field is set.
   */
  @java.lang.Override
  public boolean hasGroup() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .Group group = 1;</code>
   * @return The group.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Group getGroup() {
    return group_ == null ? org.matrix.dma.gchat.proto.Group.getDefaultInstance() : group_;
  }
  /**
   * <code>optional .Group group = 1;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.GroupOrBuilder getGroupOrBuilder() {
    return group_ == null ? org.matrix.dma.gchat.proto.Group.getDefaultInstance() : group_;
  }

  public static final int MEMBERSHIPS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.Membership> memberships_;
  /**
   * <code>repeated .Membership memberships = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.Membership> getMembershipsList() {
    return memberships_;
  }
  /**
   * <code>repeated .Membership memberships = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MembershipOrBuilder> 
      getMembershipsOrBuilderList() {
    return memberships_;
  }
  /**
   * <code>repeated .Membership memberships = 4;</code>
   */
  @java.lang.Override
  public int getMembershipsCount() {
    return memberships_.size();
  }
  /**
   * <code>repeated .Membership memberships = 4;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Membership getMemberships(int index) {
    return memberships_.get(index);
  }
  /**
   * <code>repeated .Membership memberships = 4;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MembershipOrBuilder getMembershipsOrBuilder(
      int index) {
    return memberships_.get(index);
  }

  public static final int USER_REVISION_FIELD_NUMBER = 2;
  private org.matrix.dma.gchat.proto.ReadRevision userRevision_;
  /**
   * <code>optional .ReadRevision user_revision = 2;</code>
   * @return Whether the userRevision field is set.
   */
  @java.lang.Override
  public boolean hasUserRevision() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .ReadRevision user_revision = 2;</code>
   * @return The userRevision.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevision getUserRevision() {
    return userRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : userRevision_;
  }
  /**
   * <code>optional .ReadRevision user_revision = 2;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getUserRevisionOrBuilder() {
    return userRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : userRevision_;
  }

  public static final int GROUP_REVISION_FIELD_NUMBER = 3;
  private org.matrix.dma.gchat.proto.ReadRevision groupRevision_;
  /**
   * <code>optional .ReadRevision group_revision = 3;</code>
   * @return Whether the groupRevision field is set.
   */
  @java.lang.Override
  public boolean hasGroupRevision() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .ReadRevision group_revision = 3;</code>
   * @return The groupRevision.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevision getGroupRevision() {
    return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
  }
  /**
   * <code>optional .ReadRevision group_revision = 3;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getGroupRevisionOrBuilder() {
    return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
  }

  public static final int MEMBERSHIP_STATE_FIELD_NUMBER = 6;
  private int membershipState_ = 0;
  /**
   * <code>optional .MembershipState membership_state = 6;</code>
   * @return Whether the membershipState field is set.
   */
  @java.lang.Override public boolean hasMembershipState() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .MembershipState membership_state = 6;</code>
   * @return The membershipState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.MembershipState getMembershipState() {
    org.matrix.dma.gchat.proto.MembershipState result = org.matrix.dma.gchat.proto.MembershipState.forNumber(membershipState_);
    return result == null ? org.matrix.dma.gchat.proto.MembershipState.MEMBER_UNKNOWN : result;
  }

  public static final int JOINED_MEMBER_IDS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.MemberId> joinedMemberIds_;
  /**
   * <code>repeated .MemberId joined_member_ids = 7;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.MemberId> getJoinedMemberIdsList() {
    return joinedMemberIds_;
  }
  /**
   * <code>repeated .MemberId joined_member_ids = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
      getJoinedMemberIdsOrBuilderList() {
    return joinedMemberIds_;
  }
  /**
   * <code>repeated .MemberId joined_member_ids = 7;</code>
   */
  @java.lang.Override
  public int getJoinedMemberIdsCount() {
    return joinedMemberIds_.size();
  }
  /**
   * <code>repeated .MemberId joined_member_ids = 7;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberId getJoinedMemberIds(int index) {
    return joinedMemberIds_.get(index);
  }
  /**
   * <code>repeated .MemberId joined_member_ids = 7;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberIdOrBuilder getJoinedMemberIdsOrBuilder(
      int index) {
    return joinedMemberIds_.get(index);
  }

  public static final int INVITED_MEMBER_IDS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.MemberId> invitedMemberIds_;
  /**
   * <code>repeated .MemberId invited_member_ids = 8;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.MemberId> getInvitedMemberIdsList() {
    return invitedMemberIds_;
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
      getInvitedMemberIdsOrBuilderList() {
    return invitedMemberIds_;
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 8;</code>
   */
  @java.lang.Override
  public int getInvitedMemberIdsCount() {
    return invitedMemberIds_.size();
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 8;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberId getInvitedMemberIds(int index) {
    return invitedMemberIds_.get(index);
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 8;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberIdOrBuilder getInvitedMemberIdsOrBuilder(
      int index) {
    return invitedMemberIds_.get(index);
  }

  public static final int READ_RECEIPT_SET_FIELD_NUMBER = 9;
  private org.matrix.dma.gchat.proto.ReadReceiptSet readReceiptSet_;
  /**
   * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
   * @return Whether the readReceiptSet field is set.
   */
  @java.lang.Override
  public boolean hasReadReceiptSet() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
   * @return The readReceiptSet.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadReceiptSet getReadReceiptSet() {
    return readReceiptSet_ == null ? org.matrix.dma.gchat.proto.ReadReceiptSet.getDefaultInstance() : readReceiptSet_;
  }
  /**
   * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadReceiptSetOrBuilder getReadReceiptSetOrBuilder() {
    return readReceiptSet_ == null ? org.matrix.dma.gchat.proto.ReadReceiptSet.getDefaultInstance() : readReceiptSet_;
  }

  public static final int SNIPPET_FIELD_NUMBER = 10;
  private org.matrix.dma.gchat.proto.Message snippet_;
  /**
   * <pre>
   * repeated ?? capabilities = 11;
   * </pre>
   *
   * <code>optional .Message snippet = 10;</code>
   * @return Whether the snippet field is set.
   */
  @java.lang.Override
  public boolean hasSnippet() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * repeated ?? capabilities = 11;
   * </pre>
   *
   * <code>optional .Message snippet = 10;</code>
   * @return The snippet.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Message getSnippet() {
    return snippet_ == null ? org.matrix.dma.gchat.proto.Message.getDefaultInstance() : snippet_;
  }
  /**
   * <pre>
   * repeated ?? capabilities = 11;
   * </pre>
   *
   * <code>optional .Message snippet = 10;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MessageOrBuilder getSnippetOrBuilder() {
    return snippet_ == null ? org.matrix.dma.gchat.proto.Message.getDefaultInstance() : snippet_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGroup());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getUserRevision());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getGroupRevision());
    }
    for (int i = 0; i < memberships_.size(); i++) {
      output.writeMessage(4, memberships_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(6, membershipState_);
    }
    for (int i = 0; i < joinedMemberIds_.size(); i++) {
      output.writeMessage(7, joinedMemberIds_.get(i));
    }
    for (int i = 0; i < invitedMemberIds_.size(); i++) {
      output.writeMessage(8, invitedMemberIds_.get(i));
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(9, getReadReceiptSet());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(10, getSnippet());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGroup());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserRevision());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGroupRevision());
    }
    for (int i = 0; i < memberships_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, memberships_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, membershipState_);
    }
    for (int i = 0; i < joinedMemberIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, joinedMemberIds_.get(i));
    }
    for (int i = 0; i < invitedMemberIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, invitedMemberIds_.get(i));
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getReadReceiptSet());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getSnippet());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.GetGroupResponse)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.GetGroupResponse other = (org.matrix.dma.gchat.proto.GetGroupResponse) obj;

    if (hasGroup() != other.hasGroup()) return false;
    if (hasGroup()) {
      if (!getGroup()
          .equals(other.getGroup())) return false;
    }
    if (!getMembershipsList()
        .equals(other.getMembershipsList())) return false;
    if (hasUserRevision() != other.hasUserRevision()) return false;
    if (hasUserRevision()) {
      if (!getUserRevision()
          .equals(other.getUserRevision())) return false;
    }
    if (hasGroupRevision() != other.hasGroupRevision()) return false;
    if (hasGroupRevision()) {
      if (!getGroupRevision()
          .equals(other.getGroupRevision())) return false;
    }
    if (hasMembershipState() != other.hasMembershipState()) return false;
    if (hasMembershipState()) {
      if (membershipState_ != other.membershipState_) return false;
    }
    if (!getJoinedMemberIdsList()
        .equals(other.getJoinedMemberIdsList())) return false;
    if (!getInvitedMemberIdsList()
        .equals(other.getInvitedMemberIdsList())) return false;
    if (hasReadReceiptSet() != other.hasReadReceiptSet()) return false;
    if (hasReadReceiptSet()) {
      if (!getReadReceiptSet()
          .equals(other.getReadReceiptSet())) return false;
    }
    if (hasSnippet() != other.hasSnippet()) return false;
    if (hasSnippet()) {
      if (!getSnippet()
          .equals(other.getSnippet())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGroup()) {
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
    }
    if (getMembershipsCount() > 0) {
      hash = (37 * hash) + MEMBERSHIPS_FIELD_NUMBER;
      hash = (53 * hash) + getMembershipsList().hashCode();
    }
    if (hasUserRevision()) {
      hash = (37 * hash) + USER_REVISION_FIELD_NUMBER;
      hash = (53 * hash) + getUserRevision().hashCode();
    }
    if (hasGroupRevision()) {
      hash = (37 * hash) + GROUP_REVISION_FIELD_NUMBER;
      hash = (53 * hash) + getGroupRevision().hashCode();
    }
    if (hasMembershipState()) {
      hash = (37 * hash) + MEMBERSHIP_STATE_FIELD_NUMBER;
      hash = (53 * hash) + membershipState_;
    }
    if (getJoinedMemberIdsCount() > 0) {
      hash = (37 * hash) + JOINED_MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getJoinedMemberIdsList().hashCode();
    }
    if (getInvitedMemberIdsCount() > 0) {
      hash = (37 * hash) + INVITED_MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getInvitedMemberIdsList().hashCode();
    }
    if (hasReadReceiptSet()) {
      hash = (37 * hash) + READ_RECEIPT_SET_FIELD_NUMBER;
      hash = (53 * hash) + getReadReceiptSet().hashCode();
    }
    if (hasSnippet()) {
      hash = (37 * hash) + SNIPPET_FIELD_NUMBER;
      hash = (53 * hash) + getSnippet().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.GetGroupResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.GetGroupResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetGroupResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetGroupResponse)
      org.matrix.dma.gchat.proto.GetGroupResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_GetGroupResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_GetGroupResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.GetGroupResponse.class, org.matrix.dma.gchat.proto.GetGroupResponse.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.GetGroupResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGroupFieldBuilder();
        getMembershipsFieldBuilder();
        getUserRevisionFieldBuilder();
        getGroupRevisionFieldBuilder();
        getJoinedMemberIdsFieldBuilder();
        getInvitedMemberIdsFieldBuilder();
        getReadReceiptSetFieldBuilder();
        getSnippetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      group_ = null;
      if (groupBuilder_ != null) {
        groupBuilder_.dispose();
        groupBuilder_ = null;
      }
      if (membershipsBuilder_ == null) {
        memberships_ = java.util.Collections.emptyList();
      } else {
        memberships_ = null;
        membershipsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      userRevision_ = null;
      if (userRevisionBuilder_ != null) {
        userRevisionBuilder_.dispose();
        userRevisionBuilder_ = null;
      }
      groupRevision_ = null;
      if (groupRevisionBuilder_ != null) {
        groupRevisionBuilder_.dispose();
        groupRevisionBuilder_ = null;
      }
      membershipState_ = 0;
      if (joinedMemberIdsBuilder_ == null) {
        joinedMemberIds_ = java.util.Collections.emptyList();
      } else {
        joinedMemberIds_ = null;
        joinedMemberIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIds_ = java.util.Collections.emptyList();
      } else {
        invitedMemberIds_ = null;
        invitedMemberIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      readReceiptSet_ = null;
      if (readReceiptSetBuilder_ != null) {
        readReceiptSetBuilder_.dispose();
        readReceiptSetBuilder_ = null;
      }
      snippet_ = null;
      if (snippetBuilder_ != null) {
        snippetBuilder_.dispose();
        snippetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_GetGroupResponse_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.GetGroupResponse getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.GetGroupResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.GetGroupResponse build() {
      org.matrix.dma.gchat.proto.GetGroupResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.GetGroupResponse buildPartial() {
      org.matrix.dma.gchat.proto.GetGroupResponse result = new org.matrix.dma.gchat.proto.GetGroupResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.matrix.dma.gchat.proto.GetGroupResponse result) {
      if (membershipsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          memberships_ = java.util.Collections.unmodifiableList(memberships_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.memberships_ = memberships_;
      } else {
        result.memberships_ = membershipsBuilder_.build();
      }
      if (joinedMemberIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          joinedMemberIds_ = java.util.Collections.unmodifiableList(joinedMemberIds_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.joinedMemberIds_ = joinedMemberIds_;
      } else {
        result.joinedMemberIds_ = joinedMemberIdsBuilder_.build();
      }
      if (invitedMemberIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          invitedMemberIds_ = java.util.Collections.unmodifiableList(invitedMemberIds_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.invitedMemberIds_ = invitedMemberIds_;
      } else {
        result.invitedMemberIds_ = invitedMemberIdsBuilder_.build();
      }
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.GetGroupResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.group_ = groupBuilder_ == null
            ? group_
            : groupBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userRevision_ = userRevisionBuilder_ == null
            ? userRevision_
            : userRevisionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.groupRevision_ = groupRevisionBuilder_ == null
            ? groupRevision_
            : groupRevisionBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.membershipState_ = membershipState_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.readReceiptSet_ = readReceiptSetBuilder_ == null
            ? readReceiptSet_
            : readReceiptSetBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.snippet_ = snippetBuilder_ == null
            ? snippet_
            : snippetBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.GetGroupResponse) {
        return mergeFrom((org.matrix.dma.gchat.proto.GetGroupResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.GetGroupResponse other) {
      if (other == org.matrix.dma.gchat.proto.GetGroupResponse.getDefaultInstance()) return this;
      if (other.hasGroup()) {
        mergeGroup(other.getGroup());
      }
      if (membershipsBuilder_ == null) {
        if (!other.memberships_.isEmpty()) {
          if (memberships_.isEmpty()) {
            memberships_ = other.memberships_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMembershipsIsMutable();
            memberships_.addAll(other.memberships_);
          }
          onChanged();
        }
      } else {
        if (!other.memberships_.isEmpty()) {
          if (membershipsBuilder_.isEmpty()) {
            membershipsBuilder_.dispose();
            membershipsBuilder_ = null;
            memberships_ = other.memberships_;
            bitField0_ = (bitField0_ & ~0x00000002);
            membershipsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembershipsFieldBuilder() : null;
          } else {
            membershipsBuilder_.addAllMessages(other.memberships_);
          }
        }
      }
      if (other.hasUserRevision()) {
        mergeUserRevision(other.getUserRevision());
      }
      if (other.hasGroupRevision()) {
        mergeGroupRevision(other.getGroupRevision());
      }
      if (other.hasMembershipState()) {
        setMembershipState(other.getMembershipState());
      }
      if (joinedMemberIdsBuilder_ == null) {
        if (!other.joinedMemberIds_.isEmpty()) {
          if (joinedMemberIds_.isEmpty()) {
            joinedMemberIds_ = other.joinedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureJoinedMemberIdsIsMutable();
            joinedMemberIds_.addAll(other.joinedMemberIds_);
          }
          onChanged();
        }
      } else {
        if (!other.joinedMemberIds_.isEmpty()) {
          if (joinedMemberIdsBuilder_.isEmpty()) {
            joinedMemberIdsBuilder_.dispose();
            joinedMemberIdsBuilder_ = null;
            joinedMemberIds_ = other.joinedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
            joinedMemberIdsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJoinedMemberIdsFieldBuilder() : null;
          } else {
            joinedMemberIdsBuilder_.addAllMessages(other.joinedMemberIds_);
          }
        }
      }
      if (invitedMemberIdsBuilder_ == null) {
        if (!other.invitedMemberIds_.isEmpty()) {
          if (invitedMemberIds_.isEmpty()) {
            invitedMemberIds_ = other.invitedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureInvitedMemberIdsIsMutable();
            invitedMemberIds_.addAll(other.invitedMemberIds_);
          }
          onChanged();
        }
      } else {
        if (!other.invitedMemberIds_.isEmpty()) {
          if (invitedMemberIdsBuilder_.isEmpty()) {
            invitedMemberIdsBuilder_.dispose();
            invitedMemberIdsBuilder_ = null;
            invitedMemberIds_ = other.invitedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000040);
            invitedMemberIdsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvitedMemberIdsFieldBuilder() : null;
          } else {
            invitedMemberIdsBuilder_.addAllMessages(other.invitedMemberIds_);
          }
        }
      }
      if (other.hasReadReceiptSet()) {
        mergeReadReceiptSet(other.getReadReceiptSet());
      }
      if (other.hasSnippet()) {
        mergeSnippet(other.getSnippet());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUserRevisionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getGroupRevisionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 26
            case 34: {
              org.matrix.dma.gchat.proto.Membership m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.Membership.PARSER,
                      extensionRegistry);
              if (membershipsBuilder_ == null) {
                ensureMembershipsIsMutable();
                memberships_.add(m);
              } else {
                membershipsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 48: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.MembershipState tmpValue =
                  org.matrix.dma.gchat.proto.MembershipState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(6, tmpRaw);
              } else {
                membershipState_ = tmpRaw;
                bitField0_ |= 0x00000010;
              }
              break;
            } // case 48
            case 58: {
              org.matrix.dma.gchat.proto.MemberId m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.MemberId.PARSER,
                      extensionRegistry);
              if (joinedMemberIdsBuilder_ == null) {
                ensureJoinedMemberIdsIsMutable();
                joinedMemberIds_.add(m);
              } else {
                joinedMemberIdsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              org.matrix.dma.gchat.proto.MemberId m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.MemberId.PARSER,
                      extensionRegistry);
              if (invitedMemberIdsBuilder_ == null) {
                ensureInvitedMemberIdsIsMutable();
                invitedMemberIds_.add(m);
              } else {
                invitedMemberIdsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getReadReceiptSetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getSnippetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.matrix.dma.gchat.proto.Group group_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Group, org.matrix.dma.gchat.proto.Group.Builder, org.matrix.dma.gchat.proto.GroupOrBuilder> groupBuilder_;
    /**
     * <code>optional .Group group = 1;</code>
     * @return Whether the group field is set.
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Group group = 1;</code>
     * @return The group.
     */
    public org.matrix.dma.gchat.proto.Group getGroup() {
      if (groupBuilder_ == null) {
        return group_ == null ? org.matrix.dma.gchat.proto.Group.getDefaultInstance() : group_;
      } else {
        return groupBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public Builder setGroup(org.matrix.dma.gchat.proto.Group value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        group_ = value;
      } else {
        groupBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public Builder setGroup(
        org.matrix.dma.gchat.proto.Group.Builder builderForValue) {
      if (groupBuilder_ == null) {
        group_ = builderForValue.build();
      } else {
        groupBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public Builder mergeGroup(org.matrix.dma.gchat.proto.Group value) {
      if (groupBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          group_ != null &&
          group_ != org.matrix.dma.gchat.proto.Group.getDefaultInstance()) {
          getGroupBuilder().mergeFrom(value);
        } else {
          group_ = value;
        }
      } else {
        groupBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public Builder clearGroup() {
      bitField0_ = (bitField0_ & ~0x00000001);
      group_ = null;
      if (groupBuilder_ != null) {
        groupBuilder_.dispose();
        groupBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Group.Builder getGroupBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    public org.matrix.dma.gchat.proto.GroupOrBuilder getGroupOrBuilder() {
      if (groupBuilder_ != null) {
        return groupBuilder_.getMessageOrBuilder();
      } else {
        return group_ == null ?
            org.matrix.dma.gchat.proto.Group.getDefaultInstance() : group_;
      }
    }
    /**
     * <code>optional .Group group = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Group, org.matrix.dma.gchat.proto.Group.Builder, org.matrix.dma.gchat.proto.GroupOrBuilder> 
        getGroupFieldBuilder() {
      if (groupBuilder_ == null) {
        groupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.Group, org.matrix.dma.gchat.proto.Group.Builder, org.matrix.dma.gchat.proto.GroupOrBuilder>(
                getGroup(),
                getParentForChildren(),
                isClean());
        group_ = null;
      }
      return groupBuilder_;
    }

    private java.util.List<org.matrix.dma.gchat.proto.Membership> memberships_ =
      java.util.Collections.emptyList();
    private void ensureMembershipsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        memberships_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.Membership>(memberships_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder> membershipsBuilder_;

    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Membership> getMembershipsList() {
      if (membershipsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(memberships_);
      } else {
        return membershipsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public int getMembershipsCount() {
      if (membershipsBuilder_ == null) {
        return memberships_.size();
      } else {
        return membershipsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public org.matrix.dma.gchat.proto.Membership getMemberships(int index) {
      if (membershipsBuilder_ == null) {
        return memberships_.get(index);
      } else {
        return membershipsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder setMemberships(
        int index, org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.set(index, value);
        onChanged();
      } else {
        membershipsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder setMemberships(
        int index, org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.set(index, builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder addMemberships(org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.add(value);
        onChanged();
      } else {
        membershipsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder addMemberships(
        int index, org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.add(index, value);
        onChanged();
      } else {
        membershipsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder addMemberships(
        org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.add(builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder addMemberships(
        int index, org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.add(index, builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder addAllMemberships(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.Membership> values) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memberships_);
        onChanged();
      } else {
        membershipsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder clearMemberships() {
      if (membershipsBuilder_ == null) {
        memberships_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        membershipsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public Builder removeMemberships(int index) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.remove(index);
        onChanged();
      } else {
        membershipsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder getMembershipsBuilder(
        int index) {
      return getMembershipsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public org.matrix.dma.gchat.proto.MembershipOrBuilder getMembershipsOrBuilder(
        int index) {
      if (membershipsBuilder_ == null) {
        return memberships_.get(index);  } else {
        return membershipsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MembershipOrBuilder> 
         getMembershipsOrBuilderList() {
      if (membershipsBuilder_ != null) {
        return membershipsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(memberships_);
      }
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder addMembershipsBuilder() {
      return getMembershipsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.Membership.getDefaultInstance());
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder addMembershipsBuilder(
        int index) {
      return getMembershipsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.Membership.getDefaultInstance());
    }
    /**
     * <code>repeated .Membership memberships = 4;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Membership.Builder> 
         getMembershipsBuilderList() {
      return getMembershipsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder> 
        getMembershipsFieldBuilder() {
      if (membershipsBuilder_ == null) {
        membershipsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder>(
                memberships_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        memberships_ = null;
      }
      return membershipsBuilder_;
    }

    private org.matrix.dma.gchat.proto.ReadRevision userRevision_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> userRevisionBuilder_;
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     * @return Whether the userRevision field is set.
     */
    public boolean hasUserRevision() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     * @return The userRevision.
     */
    public org.matrix.dma.gchat.proto.ReadRevision getUserRevision() {
      if (userRevisionBuilder_ == null) {
        return userRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : userRevision_;
      } else {
        return userRevisionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public Builder setUserRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (userRevisionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userRevision_ = value;
      } else {
        userRevisionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public Builder setUserRevision(
        org.matrix.dma.gchat.proto.ReadRevision.Builder builderForValue) {
      if (userRevisionBuilder_ == null) {
        userRevision_ = builderForValue.build();
      } else {
        userRevisionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public Builder mergeUserRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (userRevisionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          userRevision_ != null &&
          userRevision_ != org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance()) {
          getUserRevisionBuilder().mergeFrom(value);
        } else {
          userRevision_ = value;
        }
      } else {
        userRevisionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public Builder clearUserRevision() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userRevision_ = null;
      if (userRevisionBuilder_ != null) {
        userRevisionBuilder_.dispose();
        userRevisionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevision.Builder getUserRevisionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getUserRevisionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getUserRevisionOrBuilder() {
      if (userRevisionBuilder_ != null) {
        return userRevisionBuilder_.getMessageOrBuilder();
      } else {
        return userRevision_ == null ?
            org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : userRevision_;
      }
    }
    /**
     * <code>optional .ReadRevision user_revision = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> 
        getUserRevisionFieldBuilder() {
      if (userRevisionBuilder_ == null) {
        userRevisionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder>(
                getUserRevision(),
                getParentForChildren(),
                isClean());
        userRevision_ = null;
      }
      return userRevisionBuilder_;
    }

    private org.matrix.dma.gchat.proto.ReadRevision groupRevision_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> groupRevisionBuilder_;
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     * @return Whether the groupRevision field is set.
     */
    public boolean hasGroupRevision() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     * @return The groupRevision.
     */
    public org.matrix.dma.gchat.proto.ReadRevision getGroupRevision() {
      if (groupRevisionBuilder_ == null) {
        return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
      } else {
        return groupRevisionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public Builder setGroupRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (groupRevisionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupRevision_ = value;
      } else {
        groupRevisionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public Builder setGroupRevision(
        org.matrix.dma.gchat.proto.ReadRevision.Builder builderForValue) {
      if (groupRevisionBuilder_ == null) {
        groupRevision_ = builderForValue.build();
      } else {
        groupRevisionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public Builder mergeGroupRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (groupRevisionBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          groupRevision_ != null &&
          groupRevision_ != org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance()) {
          getGroupRevisionBuilder().mergeFrom(value);
        } else {
          groupRevision_ = value;
        }
      } else {
        groupRevisionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public Builder clearGroupRevision() {
      bitField0_ = (bitField0_ & ~0x00000008);
      groupRevision_ = null;
      if (groupRevisionBuilder_ != null) {
        groupRevisionBuilder_.dispose();
        groupRevisionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevision.Builder getGroupRevisionBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getGroupRevisionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getGroupRevisionOrBuilder() {
      if (groupRevisionBuilder_ != null) {
        return groupRevisionBuilder_.getMessageOrBuilder();
      } else {
        return groupRevision_ == null ?
            org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
      }
    }
    /**
     * <code>optional .ReadRevision group_revision = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> 
        getGroupRevisionFieldBuilder() {
      if (groupRevisionBuilder_ == null) {
        groupRevisionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder>(
                getGroupRevision(),
                getParentForChildren(),
                isClean());
        groupRevision_ = null;
      }
      return groupRevisionBuilder_;
    }

    private int membershipState_ = 0;
    /**
     * <code>optional .MembershipState membership_state = 6;</code>
     * @return Whether the membershipState field is set.
     */
    @java.lang.Override public boolean hasMembershipState() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .MembershipState membership_state = 6;</code>
     * @return The membershipState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.MembershipState getMembershipState() {
      org.matrix.dma.gchat.proto.MembershipState result = org.matrix.dma.gchat.proto.MembershipState.forNumber(membershipState_);
      return result == null ? org.matrix.dma.gchat.proto.MembershipState.MEMBER_UNKNOWN : result;
    }
    /**
     * <code>optional .MembershipState membership_state = 6;</code>
     * @param value The membershipState to set.
     * @return This builder for chaining.
     */
    public Builder setMembershipState(org.matrix.dma.gchat.proto.MembershipState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      membershipState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .MembershipState membership_state = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMembershipState() {
      bitField0_ = (bitField0_ & ~0x00000010);
      membershipState_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.matrix.dma.gchat.proto.MemberId> joinedMemberIds_ =
      java.util.Collections.emptyList();
    private void ensureJoinedMemberIdsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        joinedMemberIds_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.MemberId>(joinedMemberIds_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> joinedMemberIdsBuilder_;

    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId> getJoinedMemberIdsList() {
      if (joinedMemberIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(joinedMemberIds_);
      } else {
        return joinedMemberIdsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public int getJoinedMemberIdsCount() {
      if (joinedMemberIdsBuilder_ == null) {
        return joinedMemberIds_.size();
      } else {
        return joinedMemberIdsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId getJoinedMemberIds(int index) {
      if (joinedMemberIdsBuilder_ == null) {
        return joinedMemberIds_.get(index);
      } else {
        return joinedMemberIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder setJoinedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (joinedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.set(index, value);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder setJoinedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (joinedMemberIdsBuilder_ == null) {
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        joinedMemberIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder addJoinedMemberIds(org.matrix.dma.gchat.proto.MemberId value) {
      if (joinedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.add(value);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder addJoinedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (joinedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.add(index, value);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder addJoinedMemberIds(
        org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (joinedMemberIdsBuilder_ == null) {
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.add(builderForValue.build());
        onChanged();
      } else {
        joinedMemberIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder addJoinedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (joinedMemberIdsBuilder_ == null) {
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        joinedMemberIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder addAllJoinedMemberIds(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.MemberId> values) {
      if (joinedMemberIdsBuilder_ == null) {
        ensureJoinedMemberIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, joinedMemberIds_);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder clearJoinedMemberIds() {
      if (joinedMemberIdsBuilder_ == null) {
        joinedMemberIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public Builder removeJoinedMemberIds(int index) {
      if (joinedMemberIdsBuilder_ == null) {
        ensureJoinedMemberIdsIsMutable();
        joinedMemberIds_.remove(index);
        onChanged();
      } else {
        joinedMemberIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder getJoinedMemberIdsBuilder(
        int index) {
      return getJoinedMemberIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MemberIdOrBuilder getJoinedMemberIdsOrBuilder(
        int index) {
      if (joinedMemberIdsBuilder_ == null) {
        return joinedMemberIds_.get(index);  } else {
        return joinedMemberIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
         getJoinedMemberIdsOrBuilderList() {
      if (joinedMemberIdsBuilder_ != null) {
        return joinedMemberIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(joinedMemberIds_);
      }
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addJoinedMemberIdsBuilder() {
      return getJoinedMemberIdsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addJoinedMemberIdsBuilder(
        int index) {
      return getJoinedMemberIdsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId joined_member_ids = 7;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId.Builder> 
         getJoinedMemberIdsBuilderList() {
      return getJoinedMemberIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
        getJoinedMemberIdsFieldBuilder() {
      if (joinedMemberIdsBuilder_ == null) {
        joinedMemberIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder>(
                joinedMemberIds_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        joinedMemberIds_ = null;
      }
      return joinedMemberIdsBuilder_;
    }

    private java.util.List<org.matrix.dma.gchat.proto.MemberId> invitedMemberIds_ =
      java.util.Collections.emptyList();
    private void ensureInvitedMemberIdsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        invitedMemberIds_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.MemberId>(invitedMemberIds_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> invitedMemberIdsBuilder_;

    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId> getInvitedMemberIdsList() {
      if (invitedMemberIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invitedMemberIds_);
      } else {
        return invitedMemberIdsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public int getInvitedMemberIdsCount() {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.size();
      } else {
        return invitedMemberIdsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId getInvitedMemberIds(int index) {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.get(index);
      } else {
        return invitedMemberIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder setInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.set(index, value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder setInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder addInvitedMemberIds(org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder addInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(index, value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder addInvitedMemberIds(
        org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder addInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder addAllInvitedMemberIds(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.MemberId> values) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invitedMemberIds_);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder clearInvitedMemberIds() {
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public Builder removeInvitedMemberIds(int index) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.remove(index);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder getInvitedMemberIdsBuilder(
        int index) {
      return getInvitedMemberIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public org.matrix.dma.gchat.proto.MemberIdOrBuilder getInvitedMemberIdsOrBuilder(
        int index) {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.get(index);  } else {
        return invitedMemberIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
         getInvitedMemberIdsOrBuilderList() {
      if (invitedMemberIdsBuilder_ != null) {
        return invitedMemberIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invitedMemberIds_);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addInvitedMemberIdsBuilder() {
      return getInvitedMemberIdsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addInvitedMemberIdsBuilder(
        int index) {
      return getInvitedMemberIdsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 8;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId.Builder> 
         getInvitedMemberIdsBuilderList() {
      return getInvitedMemberIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
        getInvitedMemberIdsFieldBuilder() {
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder>(
                invitedMemberIds_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        invitedMemberIds_ = null;
      }
      return invitedMemberIdsBuilder_;
    }

    private org.matrix.dma.gchat.proto.ReadReceiptSet readReceiptSet_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadReceiptSet, org.matrix.dma.gchat.proto.ReadReceiptSet.Builder, org.matrix.dma.gchat.proto.ReadReceiptSetOrBuilder> readReceiptSetBuilder_;
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     * @return Whether the readReceiptSet field is set.
     */
    public boolean hasReadReceiptSet() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     * @return The readReceiptSet.
     */
    public org.matrix.dma.gchat.proto.ReadReceiptSet getReadReceiptSet() {
      if (readReceiptSetBuilder_ == null) {
        return readReceiptSet_ == null ? org.matrix.dma.gchat.proto.ReadReceiptSet.getDefaultInstance() : readReceiptSet_;
      } else {
        return readReceiptSetBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public Builder setReadReceiptSet(org.matrix.dma.gchat.proto.ReadReceiptSet value) {
      if (readReceiptSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        readReceiptSet_ = value;
      } else {
        readReceiptSetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public Builder setReadReceiptSet(
        org.matrix.dma.gchat.proto.ReadReceiptSet.Builder builderForValue) {
      if (readReceiptSetBuilder_ == null) {
        readReceiptSet_ = builderForValue.build();
      } else {
        readReceiptSetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public Builder mergeReadReceiptSet(org.matrix.dma.gchat.proto.ReadReceiptSet value) {
      if (readReceiptSetBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          readReceiptSet_ != null &&
          readReceiptSet_ != org.matrix.dma.gchat.proto.ReadReceiptSet.getDefaultInstance()) {
          getReadReceiptSetBuilder().mergeFrom(value);
        } else {
          readReceiptSet_ = value;
        }
      } else {
        readReceiptSetBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public Builder clearReadReceiptSet() {
      bitField0_ = (bitField0_ & ~0x00000080);
      readReceiptSet_ = null;
      if (readReceiptSetBuilder_ != null) {
        readReceiptSetBuilder_.dispose();
        readReceiptSetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public org.matrix.dma.gchat.proto.ReadReceiptSet.Builder getReadReceiptSetBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getReadReceiptSetFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    public org.matrix.dma.gchat.proto.ReadReceiptSetOrBuilder getReadReceiptSetOrBuilder() {
      if (readReceiptSetBuilder_ != null) {
        return readReceiptSetBuilder_.getMessageOrBuilder();
      } else {
        return readReceiptSet_ == null ?
            org.matrix.dma.gchat.proto.ReadReceiptSet.getDefaultInstance() : readReceiptSet_;
      }
    }
    /**
     * <code>optional .ReadReceiptSet read_receipt_set = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadReceiptSet, org.matrix.dma.gchat.proto.ReadReceiptSet.Builder, org.matrix.dma.gchat.proto.ReadReceiptSetOrBuilder> 
        getReadReceiptSetFieldBuilder() {
      if (readReceiptSetBuilder_ == null) {
        readReceiptSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.ReadReceiptSet, org.matrix.dma.gchat.proto.ReadReceiptSet.Builder, org.matrix.dma.gchat.proto.ReadReceiptSetOrBuilder>(
                getReadReceiptSet(),
                getParentForChildren(),
                isClean());
        readReceiptSet_ = null;
      }
      return readReceiptSetBuilder_;
    }

    private org.matrix.dma.gchat.proto.Message snippet_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder> snippetBuilder_;
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     * @return Whether the snippet field is set.
     */
    public boolean hasSnippet() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     * @return The snippet.
     */
    public org.matrix.dma.gchat.proto.Message getSnippet() {
      if (snippetBuilder_ == null) {
        return snippet_ == null ? org.matrix.dma.gchat.proto.Message.getDefaultInstance() : snippet_;
      } else {
        return snippetBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public Builder setSnippet(org.matrix.dma.gchat.proto.Message value) {
      if (snippetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snippet_ = value;
      } else {
        snippetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public Builder setSnippet(
        org.matrix.dma.gchat.proto.Message.Builder builderForValue) {
      if (snippetBuilder_ == null) {
        snippet_ = builderForValue.build();
      } else {
        snippetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public Builder mergeSnippet(org.matrix.dma.gchat.proto.Message value) {
      if (snippetBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          snippet_ != null &&
          snippet_ != org.matrix.dma.gchat.proto.Message.getDefaultInstance()) {
          getSnippetBuilder().mergeFrom(value);
        } else {
          snippet_ = value;
        }
      } else {
        snippetBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public Builder clearSnippet() {
      bitField0_ = (bitField0_ & ~0x00000100);
      snippet_ = null;
      if (snippetBuilder_ != null) {
        snippetBuilder_.dispose();
        snippetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public org.matrix.dma.gchat.proto.Message.Builder getSnippetBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getSnippetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    public org.matrix.dma.gchat.proto.MessageOrBuilder getSnippetOrBuilder() {
      if (snippetBuilder_ != null) {
        return snippetBuilder_.getMessageOrBuilder();
      } else {
        return snippet_ == null ?
            org.matrix.dma.gchat.proto.Message.getDefaultInstance() : snippet_;
      }
    }
    /**
     * <pre>
     * repeated ?? capabilities = 11;
     * </pre>
     *
     * <code>optional .Message snippet = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder> 
        getSnippetFieldBuilder() {
      if (snippetBuilder_ == null) {
        snippetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder>(
                getSnippet(),
                getParentForChildren(),
                isClean());
        snippet_ = null;
      }
      return snippetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetGroupResponse)
  }

  // @@protoc_insertion_point(class_scope:GetGroupResponse)
  private static final org.matrix.dma.gchat.proto.GetGroupResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.GetGroupResponse();
  }

  public static org.matrix.dma.gchat.proto.GetGroupResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GetGroupResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetGroupResponse>() {
    @java.lang.Override
    public GetGroupResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetGroupResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetGroupResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.GetGroupResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

