//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

@kotlin.jvm.JvmName("-initializegroupVisibility")
public inline fun groupVisibility(block: org.matrix.dma.gchat.proto.GroupVisibilityKt.Dsl.() -> kotlin.Unit): org.matrix.dma.gchat.proto.GroupVisibility =
  org.matrix.dma.gchat.proto.GroupVisibilityKt.Dsl._create(org.matrix.dma.gchat.proto.GroupVisibility.newBuilder()).apply { block() }._build()
public object GroupVisibilityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.matrix.dma.gchat.proto.GroupVisibility.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.matrix.dma.gchat.proto.GroupVisibility.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.matrix.dma.gchat.proto.GroupVisibility = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.matrix.dma.gchat.proto.GroupVisibility.copy(block: org.matrix.dma.gchat.proto.GroupVisibilityKt.Dsl.() -> kotlin.Unit): org.matrix.dma.gchat.proto.GroupVisibility =
  org.matrix.dma.gchat.proto.GroupVisibilityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

