// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code JAddOnsOpenLink}
 */
public final class JAddOnsOpenLink extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JAddOnsOpenLink)
    JAddOnsOpenLinkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JAddOnsOpenLink.newBuilder() to construct.
  private JAddOnsOpenLink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JAddOnsOpenLink() {
    url_ = "";
    originalLink_ = "";
    openAs_ = 0;
    onClose_ = 0;
    loadIndicator_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JAddOnsOpenLink();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_JAddOnsOpenLink_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_JAddOnsOpenLink_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.JAddOnsOpenLink.class, org.matrix.dma.gchat.proto.JAddOnsOpenLink.Builder.class);
  }

  /**
   * Protobuf enum {@code JAddOnsOpenLink.OpenAs}
   */
  public enum OpenAs
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FULL_SIZE = 0;</code>
     */
    FULL_SIZE(0),
    /**
     * <code>OVERLAY = 1;</code>
     */
    OVERLAY(1),
    ;

    /**
     * <code>FULL_SIZE = 0;</code>
     */
    public static final int FULL_SIZE_VALUE = 0;
    /**
     * <code>OVERLAY = 1;</code>
     */
    public static final int OVERLAY_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OpenAs valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OpenAs forNumber(int value) {
      switch (value) {
        case 0: return FULL_SIZE;
        case 1: return OVERLAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpenAs>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OpenAs> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OpenAs>() {
            public OpenAs findValueByNumber(int number) {
              return OpenAs.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.JAddOnsOpenLink.getDescriptor().getEnumTypes().get(0);
    }

    private static final OpenAs[] VALUES = values();

    public static OpenAs valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OpenAs(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:JAddOnsOpenLink.OpenAs)
  }

  /**
   * Protobuf enum {@code JAddOnsOpenLink.OnClose}
   */
  public enum OnClose
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOTHING = 0;</code>
     */
    NOTHING(0),
    /**
     * <code>RELOAD_ADD_ON = 1;</code>
     */
    RELOAD_ADD_ON(1),
    ;

    /**
     * <code>NOTHING = 0;</code>
     */
    public static final int NOTHING_VALUE = 0;
    /**
     * <code>RELOAD_ADD_ON = 1;</code>
     */
    public static final int RELOAD_ADD_ON_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OnClose valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OnClose forNumber(int value) {
      switch (value) {
        case 0: return NOTHING;
        case 1: return RELOAD_ADD_ON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OnClose>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OnClose> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OnClose>() {
            public OnClose findValueByNumber(int number) {
              return OnClose.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.JAddOnsOpenLink.getDescriptor().getEnumTypes().get(1);
    }

    private static final OnClose[] VALUES = values();

    public static OnClose valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OnClose(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:JAddOnsOpenLink.OnClose)
  }

  /**
   * Protobuf enum {@code JAddOnsOpenLink.LoadIndicator}
   */
  public enum LoadIndicator
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>SPINNER = 1;</code>
     */
    SPINNER(1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>SPINNER = 1;</code>
     */
    public static final int SPINNER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LoadIndicator valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LoadIndicator forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return SPINNER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoadIndicator>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoadIndicator> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoadIndicator>() {
            public LoadIndicator findValueByNumber(int number) {
              return LoadIndicator.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.JAddOnsOpenLink.getDescriptor().getEnumTypes().get(2);
    }

    private static final LoadIndicator[] VALUES = values();

    public static LoadIndicator valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LoadIndicator(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:JAddOnsOpenLink.LoadIndicator)
  }

  private int bitField0_;
  public static final int URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <code>optional string url = 1;</code>
   * @return Whether the url field is set.
   */
  @java.lang.Override
  public boolean hasUrl() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string url = 1;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        url_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string url = 1;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_LINK_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalLink_ = "";
  /**
   * <code>optional string original_link = 5;</code>
   * @return Whether the originalLink field is set.
   */
  @java.lang.Override
  public boolean hasOriginalLink() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string original_link = 5;</code>
   * @return The originalLink.
   */
  @java.lang.Override
  public java.lang.String getOriginalLink() {
    java.lang.Object ref = originalLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        originalLink_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string original_link = 5;</code>
   * @return The bytes for originalLink.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalLinkBytes() {
    java.lang.Object ref = originalLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPEN_AS_FIELD_NUMBER = 2;
  private int openAs_ = 0;
  /**
   * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
   * @return Whether the openAs field is set.
   */
  @java.lang.Override public boolean hasOpenAs() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
   * @return The openAs.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs getOpenAs() {
    org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs.forNumber(openAs_);
    return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs.FULL_SIZE : result;
  }

  public static final int ON_CLOSE_FIELD_NUMBER = 3;
  private int onClose_ = 0;
  /**
   * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
   * @return Whether the onClose field is set.
   */
  @java.lang.Override public boolean hasOnClose() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
   * @return The onClose.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose getOnClose() {
    org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose.forNumber(onClose_);
    return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose.NOTHING : result;
  }

  public static final int LOAD_INDICATOR_FIELD_NUMBER = 4;
  private int loadIndicator_ = 0;
  /**
   * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
   * @return Whether the loadIndicator field is set.
   */
  @java.lang.Override public boolean hasLoadIndicator() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
   * @return The loadIndicator.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator getLoadIndicator() {
    org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator.forNumber(loadIndicator_);
    return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator.NONE : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(2, openAs_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(3, onClose_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(4, loadIndicator_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, originalLink_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, openAs_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, onClose_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, loadIndicator_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, originalLink_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.JAddOnsOpenLink)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.JAddOnsOpenLink other = (org.matrix.dma.gchat.proto.JAddOnsOpenLink) obj;

    if (hasUrl() != other.hasUrl()) return false;
    if (hasUrl()) {
      if (!getUrl()
          .equals(other.getUrl())) return false;
    }
    if (hasOriginalLink() != other.hasOriginalLink()) return false;
    if (hasOriginalLink()) {
      if (!getOriginalLink()
          .equals(other.getOriginalLink())) return false;
    }
    if (hasOpenAs() != other.hasOpenAs()) return false;
    if (hasOpenAs()) {
      if (openAs_ != other.openAs_) return false;
    }
    if (hasOnClose() != other.hasOnClose()) return false;
    if (hasOnClose()) {
      if (onClose_ != other.onClose_) return false;
    }
    if (hasLoadIndicator() != other.hasLoadIndicator()) return false;
    if (hasLoadIndicator()) {
      if (loadIndicator_ != other.loadIndicator_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUrl()) {
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
    }
    if (hasOriginalLink()) {
      hash = (37 * hash) + ORIGINAL_LINK_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalLink().hashCode();
    }
    if (hasOpenAs()) {
      hash = (37 * hash) + OPEN_AS_FIELD_NUMBER;
      hash = (53 * hash) + openAs_;
    }
    if (hasOnClose()) {
      hash = (37 * hash) + ON_CLOSE_FIELD_NUMBER;
      hash = (53 * hash) + onClose_;
    }
    if (hasLoadIndicator()) {
      hash = (37 * hash) + LOAD_INDICATOR_FIELD_NUMBER;
      hash = (53 * hash) + loadIndicator_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.JAddOnsOpenLink prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JAddOnsOpenLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JAddOnsOpenLink)
      org.matrix.dma.gchat.proto.JAddOnsOpenLinkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_JAddOnsOpenLink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_JAddOnsOpenLink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.JAddOnsOpenLink.class, org.matrix.dma.gchat.proto.JAddOnsOpenLink.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.JAddOnsOpenLink.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      url_ = "";
      originalLink_ = "";
      openAs_ = 0;
      onClose_ = 0;
      loadIndicator_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_JAddOnsOpenLink_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.JAddOnsOpenLink.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink build() {
      org.matrix.dma.gchat.proto.JAddOnsOpenLink result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink buildPartial() {
      org.matrix.dma.gchat.proto.JAddOnsOpenLink result = new org.matrix.dma.gchat.proto.JAddOnsOpenLink(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.JAddOnsOpenLink result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.url_ = url_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.originalLink_ = originalLink_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.openAs_ = openAs_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.onClose_ = onClose_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.loadIndicator_ = loadIndicator_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.JAddOnsOpenLink) {
        return mergeFrom((org.matrix.dma.gchat.proto.JAddOnsOpenLink)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.JAddOnsOpenLink other) {
      if (other == org.matrix.dma.gchat.proto.JAddOnsOpenLink.getDefaultInstance()) return this;
      if (other.hasUrl()) {
        url_ = other.url_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOriginalLink()) {
        originalLink_ = other.originalLink_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasOpenAs()) {
        setOpenAs(other.getOpenAs());
      }
      if (other.hasOnClose()) {
        setOnClose(other.getOnClose());
      }
      if (other.hasLoadIndicator()) {
        setLoadIndicator(other.getLoadIndicator());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              url_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs tmpValue =
                  org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(2, tmpRaw);
              } else {
                openAs_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 16
            case 24: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose tmpValue =
                  org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(3, tmpRaw);
              } else {
                onClose_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 24
            case 32: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator tmpValue =
                  org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                loadIndicator_ = tmpRaw;
                bitField0_ |= 0x00000010;
              }
              break;
            } // case 32
            case 42: {
              originalLink_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object url_ = "";
    /**
     * <code>optional string url = 1;</code>
     * @return Whether the url field is set.
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string url = 1;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string url = 1;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string url = 1;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string url = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string url = 1;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object originalLink_ = "";
    /**
     * <code>optional string original_link = 5;</code>
     * @return Whether the originalLink field is set.
     */
    public boolean hasOriginalLink() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string original_link = 5;</code>
     * @return The originalLink.
     */
    public java.lang.String getOriginalLink() {
      java.lang.Object ref = originalLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          originalLink_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string original_link = 5;</code>
     * @return The bytes for originalLink.
     */
    public com.google.protobuf.ByteString
        getOriginalLinkBytes() {
      java.lang.Object ref = originalLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string original_link = 5;</code>
     * @param value The originalLink to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalLink(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalLink_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string original_link = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalLink() {
      originalLink_ = getDefaultInstance().getOriginalLink();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string original_link = 5;</code>
     * @param value The bytes for originalLink to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      originalLink_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int openAs_ = 0;
    /**
     * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
     * @return Whether the openAs field is set.
     */
    @java.lang.Override public boolean hasOpenAs() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
     * @return The openAs.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs getOpenAs() {
      org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs.forNumber(openAs_);
      return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs.FULL_SIZE : result;
    }
    /**
     * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
     * @param value The openAs to set.
     * @return This builder for chaining.
     */
    public Builder setOpenAs(org.matrix.dma.gchat.proto.JAddOnsOpenLink.OpenAs value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      openAs_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .JAddOnsOpenLink.OpenAs open_as = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpenAs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      openAs_ = 0;
      onChanged();
      return this;
    }

    private int onClose_ = 0;
    /**
     * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
     * @return Whether the onClose field is set.
     */
    @java.lang.Override public boolean hasOnClose() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
     * @return The onClose.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose getOnClose() {
      org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose.forNumber(onClose_);
      return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose.NOTHING : result;
    }
    /**
     * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
     * @param value The onClose to set.
     * @return This builder for chaining.
     */
    public Builder setOnClose(org.matrix.dma.gchat.proto.JAddOnsOpenLink.OnClose value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      onClose_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .JAddOnsOpenLink.OnClose on_close = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnClose() {
      bitField0_ = (bitField0_ & ~0x00000008);
      onClose_ = 0;
      onChanged();
      return this;
    }

    private int loadIndicator_ = 0;
    /**
     * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
     * @return Whether the loadIndicator field is set.
     */
    @java.lang.Override public boolean hasLoadIndicator() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
     * @return The loadIndicator.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator getLoadIndicator() {
      org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator result = org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator.forNumber(loadIndicator_);
      return result == null ? org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator.NONE : result;
    }
    /**
     * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
     * @param value The loadIndicator to set.
     * @return This builder for chaining.
     */
    public Builder setLoadIndicator(org.matrix.dma.gchat.proto.JAddOnsOpenLink.LoadIndicator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      loadIndicator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .JAddOnsOpenLink.LoadIndicator load_indicator = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoadIndicator() {
      bitField0_ = (bitField0_ & ~0x00000010);
      loadIndicator_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:JAddOnsOpenLink)
  }

  // @@protoc_insertion_point(class_scope:JAddOnsOpenLink)
  private static final org.matrix.dma.gchat.proto.JAddOnsOpenLink DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.JAddOnsOpenLink();
  }

  public static org.matrix.dma.gchat.proto.JAddOnsOpenLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<JAddOnsOpenLink>
      PARSER = new com.google.protobuf.AbstractParser<JAddOnsOpenLink>() {
    @java.lang.Override
    public JAddOnsOpenLink parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JAddOnsOpenLink> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JAddOnsOpenLink> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.JAddOnsOpenLink getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

