// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

public interface JAddOnsOnClickOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JAddOnsOnClick)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *oneof DataCase {
   * </pre>
   *
   * <code>optional string link = 1;</code>
   * @return Whether the link field is set.
   */
  boolean hasLink();
  /**
   * <pre>
   *oneof DataCase {
   * </pre>
   *
   * <code>optional string link = 1;</code>
   * @return The link.
   */
  java.lang.String getLink();
  /**
   * <pre>
   *oneof DataCase {
   * </pre>
   *
   * <code>optional string link = 1;</code>
   * @return The bytes for link.
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <code>optional .JAddOnsFormAction action = 2;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional .JAddOnsFormAction action = 2;</code>
   * @return The action.
   */
  org.matrix.dma.gchat.proto.JAddOnsFormAction getAction();
  /**
   * <code>optional .JAddOnsFormAction action = 2;</code>
   */
  org.matrix.dma.gchat.proto.JAddOnsFormActionOrBuilder getActionOrBuilder();

  /**
   * <code>optional .JAddOnsOpenLink open_link = 5;</code>
   * @return Whether the openLink field is set.
   */
  boolean hasOpenLink();
  /**
   * <code>optional .JAddOnsOpenLink open_link = 5;</code>
   * @return The openLink.
   */
  org.matrix.dma.gchat.proto.JAddOnsOpenLink getOpenLink();
  /**
   * <code>optional .JAddOnsOpenLink open_link = 5;</code>
   */
  org.matrix.dma.gchat.proto.JAddOnsOpenLinkOrBuilder getOpenLinkOrBuilder();

  /**
   * <code>optional .JAddOnsFormAction open_link_action = 7;</code>
   * @return Whether the openLinkAction field is set.
   */
  boolean hasOpenLinkAction();
  /**
   * <code>optional .JAddOnsFormAction open_link_action = 7;</code>
   * @return The openLinkAction.
   */
  org.matrix.dma.gchat.proto.JAddOnsFormAction getOpenLinkAction();
  /**
   * <code>optional .JAddOnsFormAction open_link_action = 7;</code>
   */
  org.matrix.dma.gchat.proto.JAddOnsFormActionOrBuilder getOpenLinkActionOrBuilder();

  /**
   * <pre>
   *optional	ComGoogleAppsExtensionsV1HostAppAction host_app_action = 9;
   *}
   * </pre>
   *
   * <code>optional .JAddOnsPushCard push_card = 8;</code>
   * @return Whether the pushCard field is set.
   */
  boolean hasPushCard();
  /**
   * <pre>
   *optional	ComGoogleAppsExtensionsV1HostAppAction host_app_action = 9;
   *}
   * </pre>
   *
   * <code>optional .JAddOnsPushCard push_card = 8;</code>
   * @return The pushCard.
   */
  org.matrix.dma.gchat.proto.JAddOnsPushCard getPushCard();
  /**
   * <pre>
   *optional	ComGoogleAppsExtensionsV1HostAppAction host_app_action = 9;
   *}
   * </pre>
   *
   * <code>optional .JAddOnsPushCard push_card = 8;</code>
   */
  org.matrix.dma.gchat.proto.JAddOnsPushCardOrBuilder getPushCardOrBuilder();
}
