// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code ListMembersResponse}
 */
public final class ListMembersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListMembersResponse)
    ListMembersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListMembersResponse.newBuilder() to construct.
  private ListMembersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListMembersResponse() {
    memberships_ = java.util.Collections.emptyList();
    members_ = java.util.Collections.emptyList();
    memberIds_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
    invitedMemberIds_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListMembersResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_ListMembersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_ListMembersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.ListMembersResponse.class, org.matrix.dma.gchat.proto.ListMembersResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MEMBERSHIPS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.Membership> memberships_;
  /**
   * <code>repeated .Membership memberships = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.Membership> getMembershipsList() {
    return memberships_;
  }
  /**
   * <code>repeated .Membership memberships = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MembershipOrBuilder> 
      getMembershipsOrBuilderList() {
    return memberships_;
  }
  /**
   * <code>repeated .Membership memberships = 1;</code>
   */
  @java.lang.Override
  public int getMembershipsCount() {
    return memberships_.size();
  }
  /**
   * <code>repeated .Membership memberships = 1;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Membership getMemberships(int index) {
    return memberships_.get(index);
  }
  /**
   * <code>repeated .Membership memberships = 1;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MembershipOrBuilder getMembershipsOrBuilder(
      int index) {
    return memberships_.get(index);
  }

  public static final int MEMBERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.Member> members_;
  /**
   * <code>repeated .Member members = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.Member> getMembersList() {
    return members_;
  }
  /**
   * <code>repeated .Member members = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MemberOrBuilder> 
      getMembersOrBuilderList() {
    return members_;
  }
  /**
   * <code>repeated .Member members = 2;</code>
   */
  @java.lang.Override
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated .Member members = 2;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Member getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated .Member members = 2;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberOrBuilder getMembersOrBuilder(
      int index) {
    return members_.get(index);
  }

  public static final int MEMBER_IDS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.MemberId> memberIds_;
  /**
   * <code>repeated .MemberId member_ids = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.MemberId> getMemberIdsList() {
    return memberIds_;
  }
  /**
   * <code>repeated .MemberId member_ids = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
      getMemberIdsOrBuilderList() {
    return memberIds_;
  }
  /**
   * <code>repeated .MemberId member_ids = 5;</code>
   */
  @java.lang.Override
  public int getMemberIdsCount() {
    return memberIds_.size();
  }
  /**
   * <code>repeated .MemberId member_ids = 5;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberId getMemberIds(int index) {
    return memberIds_.get(index);
  }
  /**
   * <code>repeated .MemberId member_ids = 5;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberIdOrBuilder getMemberIdsOrBuilder(
      int index) {
    return memberIds_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextPageToken_ = "";
  /**
   * <code>optional string next_page_token = 3;</code>
   * @return Whether the nextPageToken field is set.
   */
  @java.lang.Override
  public boolean hasNextPageToken() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string next_page_token = 3;</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nextPageToken_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string next_page_token = 3;</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_REVISION_FIELD_NUMBER = 4;
  private org.matrix.dma.gchat.proto.ReadRevision groupRevision_;
  /**
   * <code>optional .ReadRevision group_revision = 4;</code>
   * @return Whether the groupRevision field is set.
   */
  @java.lang.Override
  public boolean hasGroupRevision() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .ReadRevision group_revision = 4;</code>
   * @return The groupRevision.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevision getGroupRevision() {
    return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
  }
  /**
   * <code>optional .ReadRevision group_revision = 4;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getGroupRevisionOrBuilder() {
    return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
  }

  public static final int INVITED_MEMBER_IDS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.MemberId> invitedMemberIds_;
  /**
   * <code>repeated .MemberId invited_member_ids = 6;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.MemberId> getInvitedMemberIdsList() {
    return invitedMemberIds_;
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
      getInvitedMemberIdsOrBuilderList() {
    return invitedMemberIds_;
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 6;</code>
   */
  @java.lang.Override
  public int getInvitedMemberIdsCount() {
    return invitedMemberIds_.size();
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 6;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberId getInvitedMemberIds(int index) {
    return invitedMemberIds_.get(index);
  }
  /**
   * <code>repeated .MemberId invited_member_ids = 6;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MemberIdOrBuilder getInvitedMemberIdsOrBuilder(
      int index) {
    return invitedMemberIds_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < memberships_.size(); i++) {
      output.writeMessage(1, memberships_.get(i));
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeMessage(2, members_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nextPageToken_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getGroupRevision());
    }
    for (int i = 0; i < memberIds_.size(); i++) {
      output.writeMessage(5, memberIds_.get(i));
    }
    for (int i = 0; i < invitedMemberIds_.size(); i++) {
      output.writeMessage(6, invitedMemberIds_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < memberships_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, memberships_.get(i));
    }
    for (int i = 0; i < members_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, members_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nextPageToken_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getGroupRevision());
    }
    for (int i = 0; i < memberIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, memberIds_.get(i));
    }
    for (int i = 0; i < invitedMemberIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, invitedMemberIds_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.ListMembersResponse)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.ListMembersResponse other = (org.matrix.dma.gchat.proto.ListMembersResponse) obj;

    if (!getMembershipsList()
        .equals(other.getMembershipsList())) return false;
    if (!getMembersList()
        .equals(other.getMembersList())) return false;
    if (!getMemberIdsList()
        .equals(other.getMemberIdsList())) return false;
    if (hasNextPageToken() != other.hasNextPageToken()) return false;
    if (hasNextPageToken()) {
      if (!getNextPageToken()
          .equals(other.getNextPageToken())) return false;
    }
    if (hasGroupRevision() != other.hasGroupRevision()) return false;
    if (hasGroupRevision()) {
      if (!getGroupRevision()
          .equals(other.getGroupRevision())) return false;
    }
    if (!getInvitedMemberIdsList()
        .equals(other.getInvitedMemberIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMembershipsCount() > 0) {
      hash = (37 * hash) + MEMBERSHIPS_FIELD_NUMBER;
      hash = (53 * hash) + getMembershipsList().hashCode();
    }
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    if (getMemberIdsCount() > 0) {
      hash = (37 * hash) + MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberIdsList().hashCode();
    }
    if (hasNextPageToken()) {
      hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getNextPageToken().hashCode();
    }
    if (hasGroupRevision()) {
      hash = (37 * hash) + GROUP_REVISION_FIELD_NUMBER;
      hash = (53 * hash) + getGroupRevision().hashCode();
    }
    if (getInvitedMemberIdsCount() > 0) {
      hash = (37 * hash) + INVITED_MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getInvitedMemberIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.ListMembersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.ListMembersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListMembersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListMembersResponse)
      org.matrix.dma.gchat.proto.ListMembersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_ListMembersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_ListMembersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.ListMembersResponse.class, org.matrix.dma.gchat.proto.ListMembersResponse.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.ListMembersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMembershipsFieldBuilder();
        getMembersFieldBuilder();
        getMemberIdsFieldBuilder();
        getGroupRevisionFieldBuilder();
        getInvitedMemberIdsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (membershipsBuilder_ == null) {
        memberships_ = java.util.Collections.emptyList();
      } else {
        memberships_ = null;
        membershipsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
      } else {
        members_ = null;
        membersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (memberIdsBuilder_ == null) {
        memberIds_ = java.util.Collections.emptyList();
      } else {
        memberIds_ = null;
        memberIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      nextPageToken_ = "";
      groupRevision_ = null;
      if (groupRevisionBuilder_ != null) {
        groupRevisionBuilder_.dispose();
        groupRevisionBuilder_ = null;
      }
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIds_ = java.util.Collections.emptyList();
      } else {
        invitedMemberIds_ = null;
        invitedMemberIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_ListMembersResponse_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.ListMembersResponse getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.ListMembersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.ListMembersResponse build() {
      org.matrix.dma.gchat.proto.ListMembersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.ListMembersResponse buildPartial() {
      org.matrix.dma.gchat.proto.ListMembersResponse result = new org.matrix.dma.gchat.proto.ListMembersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.matrix.dma.gchat.proto.ListMembersResponse result) {
      if (membershipsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          memberships_ = java.util.Collections.unmodifiableList(memberships_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.memberships_ = memberships_;
      } else {
        result.memberships_ = membershipsBuilder_.build();
      }
      if (membersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.members_ = members_;
      } else {
        result.members_ = membersBuilder_.build();
      }
      if (memberIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          memberIds_ = java.util.Collections.unmodifiableList(memberIds_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.memberIds_ = memberIds_;
      } else {
        result.memberIds_ = memberIdsBuilder_.build();
      }
      if (invitedMemberIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          invitedMemberIds_ = java.util.Collections.unmodifiableList(invitedMemberIds_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.invitedMemberIds_ = invitedMemberIds_;
      } else {
        result.invitedMemberIds_ = invitedMemberIdsBuilder_.build();
      }
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.ListMembersResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nextPageToken_ = nextPageToken_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.groupRevision_ = groupRevisionBuilder_ == null
            ? groupRevision_
            : groupRevisionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.ListMembersResponse) {
        return mergeFrom((org.matrix.dma.gchat.proto.ListMembersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.ListMembersResponse other) {
      if (other == org.matrix.dma.gchat.proto.ListMembersResponse.getDefaultInstance()) return this;
      if (membershipsBuilder_ == null) {
        if (!other.memberships_.isEmpty()) {
          if (memberships_.isEmpty()) {
            memberships_ = other.memberships_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembershipsIsMutable();
            memberships_.addAll(other.memberships_);
          }
          onChanged();
        }
      } else {
        if (!other.memberships_.isEmpty()) {
          if (membershipsBuilder_.isEmpty()) {
            membershipsBuilder_.dispose();
            membershipsBuilder_ = null;
            memberships_ = other.memberships_;
            bitField0_ = (bitField0_ & ~0x00000001);
            membershipsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembershipsFieldBuilder() : null;
          } else {
            membershipsBuilder_.addAllMessages(other.memberships_);
          }
        }
      }
      if (membersBuilder_ == null) {
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
      } else {
        if (!other.members_.isEmpty()) {
          if (membersBuilder_.isEmpty()) {
            membersBuilder_.dispose();
            membersBuilder_ = null;
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000002);
            membersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembersFieldBuilder() : null;
          } else {
            membersBuilder_.addAllMessages(other.members_);
          }
        }
      }
      if (memberIdsBuilder_ == null) {
        if (!other.memberIds_.isEmpty()) {
          if (memberIds_.isEmpty()) {
            memberIds_ = other.memberIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMemberIdsIsMutable();
            memberIds_.addAll(other.memberIds_);
          }
          onChanged();
        }
      } else {
        if (!other.memberIds_.isEmpty()) {
          if (memberIdsBuilder_.isEmpty()) {
            memberIdsBuilder_.dispose();
            memberIdsBuilder_ = null;
            memberIds_ = other.memberIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
            memberIdsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMemberIdsFieldBuilder() : null;
          } else {
            memberIdsBuilder_.addAllMessages(other.memberIds_);
          }
        }
      }
      if (other.hasNextPageToken()) {
        nextPageToken_ = other.nextPageToken_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasGroupRevision()) {
        mergeGroupRevision(other.getGroupRevision());
      }
      if (invitedMemberIdsBuilder_ == null) {
        if (!other.invitedMemberIds_.isEmpty()) {
          if (invitedMemberIds_.isEmpty()) {
            invitedMemberIds_ = other.invitedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureInvitedMemberIdsIsMutable();
            invitedMemberIds_.addAll(other.invitedMemberIds_);
          }
          onChanged();
        }
      } else {
        if (!other.invitedMemberIds_.isEmpty()) {
          if (invitedMemberIdsBuilder_.isEmpty()) {
            invitedMemberIdsBuilder_.dispose();
            invitedMemberIdsBuilder_ = null;
            invitedMemberIds_ = other.invitedMemberIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
            invitedMemberIdsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvitedMemberIdsFieldBuilder() : null;
          } else {
            invitedMemberIdsBuilder_.addAllMessages(other.invitedMemberIds_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.matrix.dma.gchat.proto.Membership m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.Membership.PARSER,
                      extensionRegistry);
              if (membershipsBuilder_ == null) {
                ensureMembershipsIsMutable();
                memberships_.add(m);
              } else {
                membershipsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              org.matrix.dma.gchat.proto.Member m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.Member.PARSER,
                      extensionRegistry);
              if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.add(m);
              } else {
                membersBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              nextPageToken_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getGroupRevisionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 34
            case 42: {
              org.matrix.dma.gchat.proto.MemberId m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.MemberId.PARSER,
                      extensionRegistry);
              if (memberIdsBuilder_ == null) {
                ensureMemberIdsIsMutable();
                memberIds_.add(m);
              } else {
                memberIdsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              org.matrix.dma.gchat.proto.MemberId m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.MemberId.PARSER,
                      extensionRegistry);
              if (invitedMemberIdsBuilder_ == null) {
                ensureInvitedMemberIdsIsMutable();
                invitedMemberIds_.add(m);
              } else {
                invitedMemberIdsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.matrix.dma.gchat.proto.Membership> memberships_ =
      java.util.Collections.emptyList();
    private void ensureMembershipsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        memberships_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.Membership>(memberships_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder> membershipsBuilder_;

    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Membership> getMembershipsList() {
      if (membershipsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(memberships_);
      } else {
        return membershipsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public int getMembershipsCount() {
      if (membershipsBuilder_ == null) {
        return memberships_.size();
      } else {
        return membershipsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Membership getMemberships(int index) {
      if (membershipsBuilder_ == null) {
        return memberships_.get(index);
      } else {
        return membershipsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder setMemberships(
        int index, org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.set(index, value);
        onChanged();
      } else {
        membershipsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder setMemberships(
        int index, org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.set(index, builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder addMemberships(org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.add(value);
        onChanged();
      } else {
        membershipsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder addMemberships(
        int index, org.matrix.dma.gchat.proto.Membership value) {
      if (membershipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipsIsMutable();
        memberships_.add(index, value);
        onChanged();
      } else {
        membershipsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder addMemberships(
        org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.add(builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder addMemberships(
        int index, org.matrix.dma.gchat.proto.Membership.Builder builderForValue) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.add(index, builderForValue.build());
        onChanged();
      } else {
        membershipsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder addAllMemberships(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.Membership> values) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memberships_);
        onChanged();
      } else {
        membershipsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder clearMemberships() {
      if (membershipsBuilder_ == null) {
        memberships_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        membershipsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public Builder removeMemberships(int index) {
      if (membershipsBuilder_ == null) {
        ensureMembershipsIsMutable();
        memberships_.remove(index);
        onChanged();
      } else {
        membershipsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder getMembershipsBuilder(
        int index) {
      return getMembershipsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public org.matrix.dma.gchat.proto.MembershipOrBuilder getMembershipsOrBuilder(
        int index) {
      if (membershipsBuilder_ == null) {
        return memberships_.get(index);  } else {
        return membershipsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MembershipOrBuilder> 
         getMembershipsOrBuilderList() {
      if (membershipsBuilder_ != null) {
        return membershipsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(memberships_);
      }
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder addMembershipsBuilder() {
      return getMembershipsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.Membership.getDefaultInstance());
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Membership.Builder addMembershipsBuilder(
        int index) {
      return getMembershipsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.Membership.getDefaultInstance());
    }
    /**
     * <code>repeated .Membership memberships = 1;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Membership.Builder> 
         getMembershipsBuilderList() {
      return getMembershipsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder> 
        getMembershipsFieldBuilder() {
      if (membershipsBuilder_ == null) {
        membershipsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.Membership, org.matrix.dma.gchat.proto.Membership.Builder, org.matrix.dma.gchat.proto.MembershipOrBuilder>(
                memberships_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        memberships_ = null;
      }
      return membershipsBuilder_;
    }

    private java.util.List<org.matrix.dma.gchat.proto.Member> members_ =
      java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        members_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.Member>(members_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Member, org.matrix.dma.gchat.proto.Member.Builder, org.matrix.dma.gchat.proto.MemberOrBuilder> membersBuilder_;

    /**
     * <code>repeated .Member members = 2;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Member> getMembersList() {
      if (membersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(members_);
      } else {
        return membersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public int getMembersCount() {
      if (membersBuilder_ == null) {
        return members_.size();
      } else {
        return membersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public org.matrix.dma.gchat.proto.Member getMembers(int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);
      } else {
        return membersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder setMembers(
        int index, org.matrix.dma.gchat.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
      } else {
        membersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder setMembers(
        int index, org.matrix.dma.gchat.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder addMembers(org.matrix.dma.gchat.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
      } else {
        membersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder addMembers(
        int index, org.matrix.dma.gchat.proto.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(index, value);
        onChanged();
      } else {
        membersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder addMembers(
        org.matrix.dma.gchat.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder addMembers(
        int index, org.matrix.dma.gchat.proto.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.Member> values) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
      } else {
        membersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder clearMembers() {
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        membersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public Builder removeMembers(int index) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.remove(index);
        onChanged();
      } else {
        membersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public org.matrix.dma.gchat.proto.Member.Builder getMembersBuilder(
        int index) {
      return getMembersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public org.matrix.dma.gchat.proto.MemberOrBuilder getMembersOrBuilder(
        int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);  } else {
        return membersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MemberOrBuilder> 
         getMembersOrBuilderList() {
      if (membersBuilder_ != null) {
        return membersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(members_);
      }
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public org.matrix.dma.gchat.proto.Member.Builder addMembersBuilder() {
      return getMembersFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public org.matrix.dma.gchat.proto.Member.Builder addMembersBuilder(
        int index) {
      return getMembersFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .Member members = 2;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Member.Builder> 
         getMembersBuilderList() {
      return getMembersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Member, org.matrix.dma.gchat.proto.Member.Builder, org.matrix.dma.gchat.proto.MemberOrBuilder> 
        getMembersFieldBuilder() {
      if (membersBuilder_ == null) {
        membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.Member, org.matrix.dma.gchat.proto.Member.Builder, org.matrix.dma.gchat.proto.MemberOrBuilder>(
                members_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        members_ = null;
      }
      return membersBuilder_;
    }

    private java.util.List<org.matrix.dma.gchat.proto.MemberId> memberIds_ =
      java.util.Collections.emptyList();
    private void ensureMemberIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        memberIds_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.MemberId>(memberIds_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> memberIdsBuilder_;

    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId> getMemberIdsList() {
      if (memberIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(memberIds_);
      } else {
        return memberIdsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public int getMemberIdsCount() {
      if (memberIdsBuilder_ == null) {
        return memberIds_.size();
      } else {
        return memberIdsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId getMemberIds(int index) {
      if (memberIdsBuilder_ == null) {
        return memberIds_.get(index);
      } else {
        return memberIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder setMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (memberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMemberIdsIsMutable();
        memberIds_.set(index, value);
        onChanged();
      } else {
        memberIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder setMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (memberIdsBuilder_ == null) {
        ensureMemberIdsIsMutable();
        memberIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        memberIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder addMemberIds(org.matrix.dma.gchat.proto.MemberId value) {
      if (memberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMemberIdsIsMutable();
        memberIds_.add(value);
        onChanged();
      } else {
        memberIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder addMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (memberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMemberIdsIsMutable();
        memberIds_.add(index, value);
        onChanged();
      } else {
        memberIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder addMemberIds(
        org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (memberIdsBuilder_ == null) {
        ensureMemberIdsIsMutable();
        memberIds_.add(builderForValue.build());
        onChanged();
      } else {
        memberIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder addMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (memberIdsBuilder_ == null) {
        ensureMemberIdsIsMutable();
        memberIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        memberIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder addAllMemberIds(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.MemberId> values) {
      if (memberIdsBuilder_ == null) {
        ensureMemberIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memberIds_);
        onChanged();
      } else {
        memberIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder clearMemberIds() {
      if (memberIdsBuilder_ == null) {
        memberIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        memberIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public Builder removeMemberIds(int index) {
      if (memberIdsBuilder_ == null) {
        ensureMemberIdsIsMutable();
        memberIds_.remove(index);
        onChanged();
      } else {
        memberIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder getMemberIdsBuilder(
        int index) {
      return getMemberIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public org.matrix.dma.gchat.proto.MemberIdOrBuilder getMemberIdsOrBuilder(
        int index) {
      if (memberIdsBuilder_ == null) {
        return memberIds_.get(index);  } else {
        return memberIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
         getMemberIdsOrBuilderList() {
      if (memberIdsBuilder_ != null) {
        return memberIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(memberIds_);
      }
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addMemberIdsBuilder() {
      return getMemberIdsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addMemberIdsBuilder(
        int index) {
      return getMemberIdsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId member_ids = 5;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId.Builder> 
         getMemberIdsBuilderList() {
      return getMemberIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
        getMemberIdsFieldBuilder() {
      if (memberIdsBuilder_ == null) {
        memberIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder>(
                memberIds_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        memberIds_ = null;
      }
      return memberIdsBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <code>optional string next_page_token = 3;</code>
     * @return Whether the nextPageToken field is set.
     */
    public boolean hasNextPageToken() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string next_page_token = 3;</code>
     * @return The nextPageToken.
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nextPageToken_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string next_page_token = 3;</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string next_page_token = 3;</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string next_page_token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string next_page_token = 3;</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private org.matrix.dma.gchat.proto.ReadRevision groupRevision_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> groupRevisionBuilder_;
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     * @return Whether the groupRevision field is set.
     */
    public boolean hasGroupRevision() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     * @return The groupRevision.
     */
    public org.matrix.dma.gchat.proto.ReadRevision getGroupRevision() {
      if (groupRevisionBuilder_ == null) {
        return groupRevision_ == null ? org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
      } else {
        return groupRevisionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public Builder setGroupRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (groupRevisionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupRevision_ = value;
      } else {
        groupRevisionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public Builder setGroupRevision(
        org.matrix.dma.gchat.proto.ReadRevision.Builder builderForValue) {
      if (groupRevisionBuilder_ == null) {
        groupRevision_ = builderForValue.build();
      } else {
        groupRevisionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public Builder mergeGroupRevision(org.matrix.dma.gchat.proto.ReadRevision value) {
      if (groupRevisionBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          groupRevision_ != null &&
          groupRevision_ != org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance()) {
          getGroupRevisionBuilder().mergeFrom(value);
        } else {
          groupRevision_ = value;
        }
      } else {
        groupRevisionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public Builder clearGroupRevision() {
      bitField0_ = (bitField0_ & ~0x00000010);
      groupRevision_ = null;
      if (groupRevisionBuilder_ != null) {
        groupRevisionBuilder_.dispose();
        groupRevisionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevision.Builder getGroupRevisionBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getGroupRevisionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    public org.matrix.dma.gchat.proto.ReadRevisionOrBuilder getGroupRevisionOrBuilder() {
      if (groupRevisionBuilder_ != null) {
        return groupRevisionBuilder_.getMessageOrBuilder();
      } else {
        return groupRevision_ == null ?
            org.matrix.dma.gchat.proto.ReadRevision.getDefaultInstance() : groupRevision_;
      }
    }
    /**
     * <code>optional .ReadRevision group_revision = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder> 
        getGroupRevisionFieldBuilder() {
      if (groupRevisionBuilder_ == null) {
        groupRevisionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.ReadRevision, org.matrix.dma.gchat.proto.ReadRevision.Builder, org.matrix.dma.gchat.proto.ReadRevisionOrBuilder>(
                getGroupRevision(),
                getParentForChildren(),
                isClean());
        groupRevision_ = null;
      }
      return groupRevisionBuilder_;
    }

    private java.util.List<org.matrix.dma.gchat.proto.MemberId> invitedMemberIds_ =
      java.util.Collections.emptyList();
    private void ensureInvitedMemberIdsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        invitedMemberIds_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.MemberId>(invitedMemberIds_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> invitedMemberIdsBuilder_;

    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId> getInvitedMemberIdsList() {
      if (invitedMemberIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invitedMemberIds_);
      } else {
        return invitedMemberIdsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public int getInvitedMemberIdsCount() {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.size();
      } else {
        return invitedMemberIdsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId getInvitedMemberIds(int index) {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.get(index);
      } else {
        return invitedMemberIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder setInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.set(index, value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder setInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder addInvitedMemberIds(org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder addInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId value) {
      if (invitedMemberIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(index, value);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder addInvitedMemberIds(
        org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder addInvitedMemberIds(
        int index, org.matrix.dma.gchat.proto.MemberId.Builder builderForValue) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder addAllInvitedMemberIds(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.MemberId> values) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invitedMemberIds_);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder clearInvitedMemberIds() {
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public Builder removeInvitedMemberIds(int index) {
      if (invitedMemberIdsBuilder_ == null) {
        ensureInvitedMemberIdsIsMutable();
        invitedMemberIds_.remove(index);
        onChanged();
      } else {
        invitedMemberIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder getInvitedMemberIdsBuilder(
        int index) {
      return getInvitedMemberIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public org.matrix.dma.gchat.proto.MemberIdOrBuilder getInvitedMemberIdsOrBuilder(
        int index) {
      if (invitedMemberIdsBuilder_ == null) {
        return invitedMemberIds_.get(index);  } else {
        return invitedMemberIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
         getInvitedMemberIdsOrBuilderList() {
      if (invitedMemberIdsBuilder_ != null) {
        return invitedMemberIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invitedMemberIds_);
      }
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addInvitedMemberIdsBuilder() {
      return getInvitedMemberIdsFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public org.matrix.dma.gchat.proto.MemberId.Builder addInvitedMemberIdsBuilder(
        int index) {
      return getInvitedMemberIdsFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.MemberId.getDefaultInstance());
    }
    /**
     * <code>repeated .MemberId invited_member_ids = 6;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.MemberId.Builder> 
         getInvitedMemberIdsBuilderList() {
      return getInvitedMemberIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder> 
        getInvitedMemberIdsFieldBuilder() {
      if (invitedMemberIdsBuilder_ == null) {
        invitedMemberIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.MemberId, org.matrix.dma.gchat.proto.MemberId.Builder, org.matrix.dma.gchat.proto.MemberIdOrBuilder>(
                invitedMemberIds_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        invitedMemberIds_ = null;
      }
      return invitedMemberIdsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListMembersResponse)
  }

  // @@protoc_insertion_point(class_scope:ListMembersResponse)
  private static final org.matrix.dma.gchat.proto.ListMembersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.ListMembersResponse();
  }

  public static org.matrix.dma.gchat.proto.ListMembersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ListMembersResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListMembersResponse>() {
    @java.lang.Override
    public ListMembersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListMembersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListMembersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.ListMembersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

