// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code Reaction}
 */
public final class Reaction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Reaction)
    ReactionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Reaction.newBuilder() to construct.
  private Reaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reaction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Reaction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Reaction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Reaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.Reaction.class, org.matrix.dma.gchat.proto.Reaction.Builder.class);
  }

  private int bitField0_;
  public static final int EMOJI_FIELD_NUMBER = 1;
  private org.matrix.dma.gchat.proto.Emoji emoji_;
  /**
   * <code>optional .Emoji emoji = 1;</code>
   * @return Whether the emoji field is set.
   */
  @java.lang.Override
  public boolean hasEmoji() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .Emoji emoji = 1;</code>
   * @return The emoji.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Emoji getEmoji() {
    return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
  }
  /**
   * <code>optional .Emoji emoji = 1;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.EmojiOrBuilder getEmojiOrBuilder() {
    return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_ = 0;
  /**
   * <code>optional int32 count = 2;</code>
   * @return Whether the count field is set.
   */
  @java.lang.Override
  public boolean hasCount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 count = 2;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  public static final int CURRENT_USER_PARTICIPATED_FIELD_NUMBER = 3;
  private boolean currentUserParticipated_ = false;
  /**
   * <code>optional bool current_user_participated = 3;</code>
   * @return Whether the currentUserParticipated field is set.
   */
  @java.lang.Override
  public boolean hasCurrentUserParticipated() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool current_user_participated = 3;</code>
   * @return The currentUserParticipated.
   */
  @java.lang.Override
  public boolean getCurrentUserParticipated() {
    return currentUserParticipated_;
  }

  public static final int CREATE_TIMESTAMP_FIELD_NUMBER = 4;
  private long createTimestamp_ = 0L;
  /**
   * <code>optional int64 create_timestamp = 4;</code>
   * @return Whether the createTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasCreateTimestamp() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int64 create_timestamp = 4;</code>
   * @return The createTimestamp.
   */
  @java.lang.Override
  public long getCreateTimestamp() {
    return createTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getEmoji());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, count_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(3, currentUserParticipated_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(4, createTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmoji());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, count_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, currentUserParticipated_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, createTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.Reaction)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.Reaction other = (org.matrix.dma.gchat.proto.Reaction) obj;

    if (hasEmoji() != other.hasEmoji()) return false;
    if (hasEmoji()) {
      if (!getEmoji()
          .equals(other.getEmoji())) return false;
    }
    if (hasCount() != other.hasCount()) return false;
    if (hasCount()) {
      if (getCount()
          != other.getCount()) return false;
    }
    if (hasCurrentUserParticipated() != other.hasCurrentUserParticipated()) return false;
    if (hasCurrentUserParticipated()) {
      if (getCurrentUserParticipated()
          != other.getCurrentUserParticipated()) return false;
    }
    if (hasCreateTimestamp() != other.hasCreateTimestamp()) return false;
    if (hasCreateTimestamp()) {
      if (getCreateTimestamp()
          != other.getCreateTimestamp()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmoji()) {
      hash = (37 * hash) + EMOJI_FIELD_NUMBER;
      hash = (53 * hash) + getEmoji().hashCode();
    }
    if (hasCount()) {
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
    }
    if (hasCurrentUserParticipated()) {
      hash = (37 * hash) + CURRENT_USER_PARTICIPATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCurrentUserParticipated());
    }
    if (hasCreateTimestamp()) {
      hash = (37 * hash) + CREATE_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTimestamp());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Reaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.Reaction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Reaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Reaction)
      org.matrix.dma.gchat.proto.ReactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Reaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Reaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.Reaction.class, org.matrix.dma.gchat.proto.Reaction.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.Reaction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmojiFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      emoji_ = null;
      if (emojiBuilder_ != null) {
        emojiBuilder_.dispose();
        emojiBuilder_ = null;
      }
      count_ = 0;
      currentUserParticipated_ = false;
      createTimestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Reaction_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Reaction getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.Reaction.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Reaction build() {
      org.matrix.dma.gchat.proto.Reaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Reaction buildPartial() {
      org.matrix.dma.gchat.proto.Reaction result = new org.matrix.dma.gchat.proto.Reaction(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.Reaction result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.emoji_ = emojiBuilder_ == null
            ? emoji_
            : emojiBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.count_ = count_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.currentUserParticipated_ = currentUserParticipated_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createTimestamp_ = createTimestamp_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.Reaction) {
        return mergeFrom((org.matrix.dma.gchat.proto.Reaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.Reaction other) {
      if (other == org.matrix.dma.gchat.proto.Reaction.getDefaultInstance()) return this;
      if (other.hasEmoji()) {
        mergeEmoji(other.getEmoji());
      }
      if (other.hasCount()) {
        setCount(other.getCount());
      }
      if (other.hasCurrentUserParticipated()) {
        setCurrentUserParticipated(other.getCurrentUserParticipated());
      }
      if (other.hasCreateTimestamp()) {
        setCreateTimestamp(other.getCreateTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getEmojiFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              count_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              currentUserParticipated_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              createTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.matrix.dma.gchat.proto.Emoji emoji_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder> emojiBuilder_;
    /**
     * <code>optional .Emoji emoji = 1;</code>
     * @return Whether the emoji field is set.
     */
    public boolean hasEmoji() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     * @return The emoji.
     */
    public org.matrix.dma.gchat.proto.Emoji getEmoji() {
      if (emojiBuilder_ == null) {
        return emoji_ == null ? org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
      } else {
        return emojiBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public Builder setEmoji(org.matrix.dma.gchat.proto.Emoji value) {
      if (emojiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emoji_ = value;
      } else {
        emojiBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public Builder setEmoji(
        org.matrix.dma.gchat.proto.Emoji.Builder builderForValue) {
      if (emojiBuilder_ == null) {
        emoji_ = builderForValue.build();
      } else {
        emojiBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public Builder mergeEmoji(org.matrix.dma.gchat.proto.Emoji value) {
      if (emojiBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          emoji_ != null &&
          emoji_ != org.matrix.dma.gchat.proto.Emoji.getDefaultInstance()) {
          getEmojiBuilder().mergeFrom(value);
        } else {
          emoji_ = value;
        }
      } else {
        emojiBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public Builder clearEmoji() {
      bitField0_ = (bitField0_ & ~0x00000001);
      emoji_ = null;
      if (emojiBuilder_ != null) {
        emojiBuilder_.dispose();
        emojiBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public org.matrix.dma.gchat.proto.Emoji.Builder getEmojiBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getEmojiFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    public org.matrix.dma.gchat.proto.EmojiOrBuilder getEmojiOrBuilder() {
      if (emojiBuilder_ != null) {
        return emojiBuilder_.getMessageOrBuilder();
      } else {
        return emoji_ == null ?
            org.matrix.dma.gchat.proto.Emoji.getDefaultInstance() : emoji_;
      }
    }
    /**
     * <code>optional .Emoji emoji = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder> 
        getEmojiFieldBuilder() {
      if (emojiBuilder_ == null) {
        emojiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.Emoji, org.matrix.dma.gchat.proto.Emoji.Builder, org.matrix.dma.gchat.proto.EmojiOrBuilder>(
                getEmoji(),
                getParentForChildren(),
                isClean());
        emoji_ = null;
      }
      return emojiBuilder_;
    }

    private int count_ ;
    /**
     * <code>optional int32 count = 2;</code>
     * @return Whether the count field is set.
     */
    @java.lang.Override
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>optional int32 count = 2;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      count_ = 0;
      onChanged();
      return this;
    }

    private boolean currentUserParticipated_ ;
    /**
     * <code>optional bool current_user_participated = 3;</code>
     * @return Whether the currentUserParticipated field is set.
     */
    @java.lang.Override
    public boolean hasCurrentUserParticipated() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool current_user_participated = 3;</code>
     * @return The currentUserParticipated.
     */
    @java.lang.Override
    public boolean getCurrentUserParticipated() {
      return currentUserParticipated_;
    }
    /**
     * <code>optional bool current_user_participated = 3;</code>
     * @param value The currentUserParticipated to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentUserParticipated(boolean value) {
      
      currentUserParticipated_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool current_user_participated = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentUserParticipated() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentUserParticipated_ = false;
      onChanged();
      return this;
    }

    private long createTimestamp_ ;
    /**
     * <code>optional int64 create_timestamp = 4;</code>
     * @return Whether the createTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasCreateTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 create_timestamp = 4;</code>
     * @return The createTimestamp.
     */
    @java.lang.Override
    public long getCreateTimestamp() {
      return createTimestamp_;
    }
    /**
     * <code>optional int64 create_timestamp = 4;</code>
     * @param value The createTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimestamp(long value) {
      
      createTimestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 create_timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      createTimestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Reaction)
  }

  // @@protoc_insertion_point(class_scope:Reaction)
  private static final org.matrix.dma.gchat.proto.Reaction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.Reaction();
  }

  public static org.matrix.dma.gchat.proto.Reaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Reaction>
      PARSER = new com.google.protobuf.AbstractParser<Reaction>() {
    @java.lang.Override
    public Reaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Reaction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reaction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.Reaction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

