// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code Topic}
 */
public final class Topic extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Topic)
    TopicOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Topic.newBuilder() to construct.
  private Topic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Topic() {
    replies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Topic();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Topic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Topic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.Topic.class, org.matrix.dma.gchat.proto.Topic.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private org.matrix.dma.gchat.proto.TopicId id_;
  /**
   * <code>optional .TopicId id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .TopicId id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.TopicId getId() {
    return id_ == null ? org.matrix.dma.gchat.proto.TopicId.getDefaultInstance() : id_;
  }
  /**
   * <code>optional .TopicId id = 1;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.TopicIdOrBuilder getIdOrBuilder() {
    return id_ == null ? org.matrix.dma.gchat.proto.TopicId.getDefaultInstance() : id_;
  }

  public static final int SORT_TIME_FIELD_NUMBER = 2;
  private long sortTime_ = 0L;
  /**
   * <code>optional int64 sort_time = 2;</code>
   * @return Whether the sortTime field is set.
   */
  @java.lang.Override
  public boolean hasSortTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 sort_time = 2;</code>
   * @return The sortTime.
   */
  @java.lang.Override
  public long getSortTime() {
    return sortTime_;
  }

  public static final int CREATE_TIME_USEC_FIELD_NUMBER = 15;
  private long createTimeUsec_ = 0L;
  /**
   * <code>optional int64 create_time_usec = 15;</code>
   * @return Whether the createTimeUsec field is set.
   */
  @java.lang.Override
  public boolean hasCreateTimeUsec() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 create_time_usec = 15;</code>
   * @return The createTimeUsec.
   */
  @java.lang.Override
  public long getCreateTimeUsec() {
    return createTimeUsec_;
  }

  public static final int REPLIES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<org.matrix.dma.gchat.proto.Message> replies_;
  /**
   * <code>repeated .Message replies = 7;</code>
   */
  @java.lang.Override
  public java.util.List<org.matrix.dma.gchat.proto.Message> getRepliesList() {
    return replies_;
  }
  /**
   * <code>repeated .Message replies = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.matrix.dma.gchat.proto.MessageOrBuilder> 
      getRepliesOrBuilderList() {
    return replies_;
  }
  /**
   * <code>repeated .Message replies = 7;</code>
   */
  @java.lang.Override
  public int getRepliesCount() {
    return replies_.size();
  }
  /**
   * <code>repeated .Message replies = 7;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.Message getReplies(int index) {
    return replies_.get(index);
  }
  /**
   * <code>repeated .Message replies = 7;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.MessageOrBuilder getRepliesOrBuilder(
      int index) {
    return replies_.get(index);
  }

  public static final int IS_SYSTEM_MESSAGE_FIELD_NUMBER = 12;
  private boolean isSystemMessage_ = false;
  /**
   * <pre>
   *optional DYNProtoTopicReadState topic_read_state = 11;
   * </pre>
   *
   * <code>optional bool is_system_message = 12;</code>
   * @return Whether the isSystemMessage field is set.
   */
  @java.lang.Override
  public boolean hasIsSystemMessage() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   *optional DYNProtoTopicReadState topic_read_state = 11;
   * </pre>
   *
   * <code>optional bool is_system_message = 12;</code>
   * @return The isSystemMessage.
   */
  @java.lang.Override
  public boolean getIsSystemMessage() {
    return isSystemMessage_;
  }

  public static final int RETENTION_SETTINGS_FIELD_NUMBER = 13;
  private org.matrix.dma.gchat.proto.RetentionSettings retentionSettings_;
  /**
   * <code>optional .RetentionSettings retention_settings = 13;</code>
   * @return Whether the retentionSettings field is set.
   */
  @java.lang.Override
  public boolean hasRetentionSettings() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .RetentionSettings retention_settings = 13;</code>
   * @return The retentionSettings.
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.RetentionSettings getRetentionSettings() {
    return retentionSettings_ == null ? org.matrix.dma.gchat.proto.RetentionSettings.getDefaultInstance() : retentionSettings_;
  }
  /**
   * <code>optional .RetentionSettings retention_settings = 13;</code>
   */
  @java.lang.Override
  public org.matrix.dma.gchat.proto.RetentionSettingsOrBuilder getRetentionSettingsOrBuilder() {
    return retentionSettings_ == null ? org.matrix.dma.gchat.proto.RetentionSettings.getDefaultInstance() : retentionSettings_;
  }

  public static final int CONTAINS_MORE_UNREAD_REPLIES_FIELD_NUMBER = 14;
  private boolean containsMoreUnreadReplies_ = false;
  /**
   * <code>optional bool contains_more_unread_replies = 14;</code>
   * @return Whether the containsMoreUnreadReplies field is set.
   */
  @java.lang.Override
  public boolean hasContainsMoreUnreadReplies() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional bool contains_more_unread_replies = 14;</code>
   * @return The containsMoreUnreadReplies.
   */
  @java.lang.Override
  public boolean getContainsMoreUnreadReplies() {
    return containsMoreUnreadReplies_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getId());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, sortTime_);
    }
    for (int i = 0; i < replies_.size(); i++) {
      output.writeMessage(7, replies_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(12, isSystemMessage_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(13, getRetentionSettings());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBool(14, containsMoreUnreadReplies_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(15, createTimeUsec_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, sortTime_);
    }
    for (int i = 0; i < replies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, replies_.get(i));
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, isSystemMessage_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getRetentionSettings());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, containsMoreUnreadReplies_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, createTimeUsec_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.Topic)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.Topic other = (org.matrix.dma.gchat.proto.Topic) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasSortTime() != other.hasSortTime()) return false;
    if (hasSortTime()) {
      if (getSortTime()
          != other.getSortTime()) return false;
    }
    if (hasCreateTimeUsec() != other.hasCreateTimeUsec()) return false;
    if (hasCreateTimeUsec()) {
      if (getCreateTimeUsec()
          != other.getCreateTimeUsec()) return false;
    }
    if (!getRepliesList()
        .equals(other.getRepliesList())) return false;
    if (hasIsSystemMessage() != other.hasIsSystemMessage()) return false;
    if (hasIsSystemMessage()) {
      if (getIsSystemMessage()
          != other.getIsSystemMessage()) return false;
    }
    if (hasRetentionSettings() != other.hasRetentionSettings()) return false;
    if (hasRetentionSettings()) {
      if (!getRetentionSettings()
          .equals(other.getRetentionSettings())) return false;
    }
    if (hasContainsMoreUnreadReplies() != other.hasContainsMoreUnreadReplies()) return false;
    if (hasContainsMoreUnreadReplies()) {
      if (getContainsMoreUnreadReplies()
          != other.getContainsMoreUnreadReplies()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasSortTime()) {
      hash = (37 * hash) + SORT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSortTime());
    }
    if (hasCreateTimeUsec()) {
      hash = (37 * hash) + CREATE_TIME_USEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTimeUsec());
    }
    if (getRepliesCount() > 0) {
      hash = (37 * hash) + REPLIES_FIELD_NUMBER;
      hash = (53 * hash) + getRepliesList().hashCode();
    }
    if (hasIsSystemMessage()) {
      hash = (37 * hash) + IS_SYSTEM_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSystemMessage());
    }
    if (hasRetentionSettings()) {
      hash = (37 * hash) + RETENTION_SETTINGS_FIELD_NUMBER;
      hash = (53 * hash) + getRetentionSettings().hashCode();
    }
    if (hasContainsMoreUnreadReplies()) {
      hash = (37 * hash) + CONTAINS_MORE_UNREAD_REPLIES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getContainsMoreUnreadReplies());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Topic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Topic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.Topic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.Topic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Topic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Topic)
      org.matrix.dma.gchat.proto.TopicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Topic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Topic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.Topic.class, org.matrix.dma.gchat.proto.Topic.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.Topic.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIdFieldBuilder();
        getRepliesFieldBuilder();
        getRetentionSettingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      sortTime_ = 0L;
      createTimeUsec_ = 0L;
      if (repliesBuilder_ == null) {
        replies_ = java.util.Collections.emptyList();
      } else {
        replies_ = null;
        repliesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      isSystemMessage_ = false;
      retentionSettings_ = null;
      if (retentionSettingsBuilder_ != null) {
        retentionSettingsBuilder_.dispose();
        retentionSettingsBuilder_ = null;
      }
      containsMoreUnreadReplies_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_Topic_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Topic getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.Topic.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Topic build() {
      org.matrix.dma.gchat.proto.Topic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.Topic buildPartial() {
      org.matrix.dma.gchat.proto.Topic result = new org.matrix.dma.gchat.proto.Topic(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.matrix.dma.gchat.proto.Topic result) {
      if (repliesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          replies_ = java.util.Collections.unmodifiableList(replies_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.replies_ = replies_;
      } else {
        result.replies_ = repliesBuilder_.build();
      }
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.Topic result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sortTime_ = sortTime_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createTimeUsec_ = createTimeUsec_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isSystemMessage_ = isSystemMessage_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.retentionSettings_ = retentionSettingsBuilder_ == null
            ? retentionSettings_
            : retentionSettingsBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.containsMoreUnreadReplies_ = containsMoreUnreadReplies_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.Topic) {
        return mergeFrom((org.matrix.dma.gchat.proto.Topic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.Topic other) {
      if (other == org.matrix.dma.gchat.proto.Topic.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasSortTime()) {
        setSortTime(other.getSortTime());
      }
      if (other.hasCreateTimeUsec()) {
        setCreateTimeUsec(other.getCreateTimeUsec());
      }
      if (repliesBuilder_ == null) {
        if (!other.replies_.isEmpty()) {
          if (replies_.isEmpty()) {
            replies_ = other.replies_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRepliesIsMutable();
            replies_.addAll(other.replies_);
          }
          onChanged();
        }
      } else {
        if (!other.replies_.isEmpty()) {
          if (repliesBuilder_.isEmpty()) {
            repliesBuilder_.dispose();
            repliesBuilder_ = null;
            replies_ = other.replies_;
            bitField0_ = (bitField0_ & ~0x00000008);
            repliesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRepliesFieldBuilder() : null;
          } else {
            repliesBuilder_.addAllMessages(other.replies_);
          }
        }
      }
      if (other.hasIsSystemMessage()) {
        setIsSystemMessage(other.getIsSystemMessage());
      }
      if (other.hasRetentionSettings()) {
        mergeRetentionSettings(other.getRetentionSettings());
      }
      if (other.hasContainsMoreUnreadReplies()) {
        setContainsMoreUnreadReplies(other.getContainsMoreUnreadReplies());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              sortTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 58: {
              org.matrix.dma.gchat.proto.Message m =
                  input.readMessage(
                      org.matrix.dma.gchat.proto.Message.PARSER,
                      extensionRegistry);
              if (repliesBuilder_ == null) {
                ensureRepliesIsMutable();
                replies_.add(m);
              } else {
                repliesBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 96: {
              isSystemMessage_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 96
            case 106: {
              input.readMessage(
                  getRetentionSettingsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 106
            case 112: {
              containsMoreUnreadReplies_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 112
            case 120: {
              createTimeUsec_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 120
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.matrix.dma.gchat.proto.TopicId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.TopicId, org.matrix.dma.gchat.proto.TopicId.Builder, org.matrix.dma.gchat.proto.TopicIdOrBuilder> idBuilder_;
    /**
     * <code>optional .TopicId id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     * @return The id.
     */
    public org.matrix.dma.gchat.proto.TopicId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? org.matrix.dma.gchat.proto.TopicId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public Builder setId(org.matrix.dma.gchat.proto.TopicId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public Builder setId(
        org.matrix.dma.gchat.proto.TopicId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public Builder mergeId(org.matrix.dma.gchat.proto.TopicId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != org.matrix.dma.gchat.proto.TopicId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public org.matrix.dma.gchat.proto.TopicId.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    public org.matrix.dma.gchat.proto.TopicIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            org.matrix.dma.gchat.proto.TopicId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>optional .TopicId id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.TopicId, org.matrix.dma.gchat.proto.TopicId.Builder, org.matrix.dma.gchat.proto.TopicIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.TopicId, org.matrix.dma.gchat.proto.TopicId.Builder, org.matrix.dma.gchat.proto.TopicIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private long sortTime_ ;
    /**
     * <code>optional int64 sort_time = 2;</code>
     * @return Whether the sortTime field is set.
     */
    @java.lang.Override
    public boolean hasSortTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 sort_time = 2;</code>
     * @return The sortTime.
     */
    @java.lang.Override
    public long getSortTime() {
      return sortTime_;
    }
    /**
     * <code>optional int64 sort_time = 2;</code>
     * @param value The sortTime to set.
     * @return This builder for chaining.
     */
    public Builder setSortTime(long value) {
      
      sortTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 sort_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSortTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sortTime_ = 0L;
      onChanged();
      return this;
    }

    private long createTimeUsec_ ;
    /**
     * <code>optional int64 create_time_usec = 15;</code>
     * @return Whether the createTimeUsec field is set.
     */
    @java.lang.Override
    public boolean hasCreateTimeUsec() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 create_time_usec = 15;</code>
     * @return The createTimeUsec.
     */
    @java.lang.Override
    public long getCreateTimeUsec() {
      return createTimeUsec_;
    }
    /**
     * <code>optional int64 create_time_usec = 15;</code>
     * @param value The createTimeUsec to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimeUsec(long value) {
      
      createTimeUsec_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 create_time_usec = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTimeUsec() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createTimeUsec_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.matrix.dma.gchat.proto.Message> replies_ =
      java.util.Collections.emptyList();
    private void ensureRepliesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        replies_ = new java.util.ArrayList<org.matrix.dma.gchat.proto.Message>(replies_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder> repliesBuilder_;

    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Message> getRepliesList() {
      if (repliesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(replies_);
      } else {
        return repliesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public int getRepliesCount() {
      if (repliesBuilder_ == null) {
        return replies_.size();
      } else {
        return repliesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public org.matrix.dma.gchat.proto.Message getReplies(int index) {
      if (repliesBuilder_ == null) {
        return replies_.get(index);
      } else {
        return repliesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder setReplies(
        int index, org.matrix.dma.gchat.proto.Message value) {
      if (repliesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesIsMutable();
        replies_.set(index, value);
        onChanged();
      } else {
        repliesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder setReplies(
        int index, org.matrix.dma.gchat.proto.Message.Builder builderForValue) {
      if (repliesBuilder_ == null) {
        ensureRepliesIsMutable();
        replies_.set(index, builderForValue.build());
        onChanged();
      } else {
        repliesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder addReplies(org.matrix.dma.gchat.proto.Message value) {
      if (repliesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesIsMutable();
        replies_.add(value);
        onChanged();
      } else {
        repliesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder addReplies(
        int index, org.matrix.dma.gchat.proto.Message value) {
      if (repliesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesIsMutable();
        replies_.add(index, value);
        onChanged();
      } else {
        repliesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder addReplies(
        org.matrix.dma.gchat.proto.Message.Builder builderForValue) {
      if (repliesBuilder_ == null) {
        ensureRepliesIsMutable();
        replies_.add(builderForValue.build());
        onChanged();
      } else {
        repliesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder addReplies(
        int index, org.matrix.dma.gchat.proto.Message.Builder builderForValue) {
      if (repliesBuilder_ == null) {
        ensureRepliesIsMutable();
        replies_.add(index, builderForValue.build());
        onChanged();
      } else {
        repliesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder addAllReplies(
        java.lang.Iterable<? extends org.matrix.dma.gchat.proto.Message> values) {
      if (repliesBuilder_ == null) {
        ensureRepliesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, replies_);
        onChanged();
      } else {
        repliesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder clearReplies() {
      if (repliesBuilder_ == null) {
        replies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        repliesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public Builder removeReplies(int index) {
      if (repliesBuilder_ == null) {
        ensureRepliesIsMutable();
        replies_.remove(index);
        onChanged();
      } else {
        repliesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public org.matrix.dma.gchat.proto.Message.Builder getRepliesBuilder(
        int index) {
      return getRepliesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public org.matrix.dma.gchat.proto.MessageOrBuilder getRepliesOrBuilder(
        int index) {
      if (repliesBuilder_ == null) {
        return replies_.get(index);  } else {
        return repliesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public java.util.List<? extends org.matrix.dma.gchat.proto.MessageOrBuilder> 
         getRepliesOrBuilderList() {
      if (repliesBuilder_ != null) {
        return repliesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(replies_);
      }
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public org.matrix.dma.gchat.proto.Message.Builder addRepliesBuilder() {
      return getRepliesFieldBuilder().addBuilder(
          org.matrix.dma.gchat.proto.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public org.matrix.dma.gchat.proto.Message.Builder addRepliesBuilder(
        int index) {
      return getRepliesFieldBuilder().addBuilder(
          index, org.matrix.dma.gchat.proto.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .Message replies = 7;</code>
     */
    public java.util.List<org.matrix.dma.gchat.proto.Message.Builder> 
         getRepliesBuilderList() {
      return getRepliesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder> 
        getRepliesFieldBuilder() {
      if (repliesBuilder_ == null) {
        repliesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.matrix.dma.gchat.proto.Message, org.matrix.dma.gchat.proto.Message.Builder, org.matrix.dma.gchat.proto.MessageOrBuilder>(
                replies_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        replies_ = null;
      }
      return repliesBuilder_;
    }

    private boolean isSystemMessage_ ;
    /**
     * <pre>
     *optional DYNProtoTopicReadState topic_read_state = 11;
     * </pre>
     *
     * <code>optional bool is_system_message = 12;</code>
     * @return Whether the isSystemMessage field is set.
     */
    @java.lang.Override
    public boolean hasIsSystemMessage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *optional DYNProtoTopicReadState topic_read_state = 11;
     * </pre>
     *
     * <code>optional bool is_system_message = 12;</code>
     * @return The isSystemMessage.
     */
    @java.lang.Override
    public boolean getIsSystemMessage() {
      return isSystemMessage_;
    }
    /**
     * <pre>
     *optional DYNProtoTopicReadState topic_read_state = 11;
     * </pre>
     *
     * <code>optional bool is_system_message = 12;</code>
     * @param value The isSystemMessage to set.
     * @return This builder for chaining.
     */
    public Builder setIsSystemMessage(boolean value) {
      
      isSystemMessage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *optional DYNProtoTopicReadState topic_read_state = 11;
     * </pre>
     *
     * <code>optional bool is_system_message = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSystemMessage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isSystemMessage_ = false;
      onChanged();
      return this;
    }

    private org.matrix.dma.gchat.proto.RetentionSettings retentionSettings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.RetentionSettings, org.matrix.dma.gchat.proto.RetentionSettings.Builder, org.matrix.dma.gchat.proto.RetentionSettingsOrBuilder> retentionSettingsBuilder_;
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     * @return Whether the retentionSettings field is set.
     */
    public boolean hasRetentionSettings() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     * @return The retentionSettings.
     */
    public org.matrix.dma.gchat.proto.RetentionSettings getRetentionSettings() {
      if (retentionSettingsBuilder_ == null) {
        return retentionSettings_ == null ? org.matrix.dma.gchat.proto.RetentionSettings.getDefaultInstance() : retentionSettings_;
      } else {
        return retentionSettingsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public Builder setRetentionSettings(org.matrix.dma.gchat.proto.RetentionSettings value) {
      if (retentionSettingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        retentionSettings_ = value;
      } else {
        retentionSettingsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public Builder setRetentionSettings(
        org.matrix.dma.gchat.proto.RetentionSettings.Builder builderForValue) {
      if (retentionSettingsBuilder_ == null) {
        retentionSettings_ = builderForValue.build();
      } else {
        retentionSettingsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public Builder mergeRetentionSettings(org.matrix.dma.gchat.proto.RetentionSettings value) {
      if (retentionSettingsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          retentionSettings_ != null &&
          retentionSettings_ != org.matrix.dma.gchat.proto.RetentionSettings.getDefaultInstance()) {
          getRetentionSettingsBuilder().mergeFrom(value);
        } else {
          retentionSettings_ = value;
        }
      } else {
        retentionSettingsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public Builder clearRetentionSettings() {
      bitField0_ = (bitField0_ & ~0x00000020);
      retentionSettings_ = null;
      if (retentionSettingsBuilder_ != null) {
        retentionSettingsBuilder_.dispose();
        retentionSettingsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public org.matrix.dma.gchat.proto.RetentionSettings.Builder getRetentionSettingsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getRetentionSettingsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    public org.matrix.dma.gchat.proto.RetentionSettingsOrBuilder getRetentionSettingsOrBuilder() {
      if (retentionSettingsBuilder_ != null) {
        return retentionSettingsBuilder_.getMessageOrBuilder();
      } else {
        return retentionSettings_ == null ?
            org.matrix.dma.gchat.proto.RetentionSettings.getDefaultInstance() : retentionSettings_;
      }
    }
    /**
     * <code>optional .RetentionSettings retention_settings = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.dma.gchat.proto.RetentionSettings, org.matrix.dma.gchat.proto.RetentionSettings.Builder, org.matrix.dma.gchat.proto.RetentionSettingsOrBuilder> 
        getRetentionSettingsFieldBuilder() {
      if (retentionSettingsBuilder_ == null) {
        retentionSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.dma.gchat.proto.RetentionSettings, org.matrix.dma.gchat.proto.RetentionSettings.Builder, org.matrix.dma.gchat.proto.RetentionSettingsOrBuilder>(
                getRetentionSettings(),
                getParentForChildren(),
                isClean());
        retentionSettings_ = null;
      }
      return retentionSettingsBuilder_;
    }

    private boolean containsMoreUnreadReplies_ ;
    /**
     * <code>optional bool contains_more_unread_replies = 14;</code>
     * @return Whether the containsMoreUnreadReplies field is set.
     */
    @java.lang.Override
    public boolean hasContainsMoreUnreadReplies() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool contains_more_unread_replies = 14;</code>
     * @return The containsMoreUnreadReplies.
     */
    @java.lang.Override
    public boolean getContainsMoreUnreadReplies() {
      return containsMoreUnreadReplies_;
    }
    /**
     * <code>optional bool contains_more_unread_replies = 14;</code>
     * @param value The containsMoreUnreadReplies to set.
     * @return This builder for chaining.
     */
    public Builder setContainsMoreUnreadReplies(boolean value) {
      
      containsMoreUnreadReplies_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool contains_more_unread_replies = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainsMoreUnreadReplies() {
      bitField0_ = (bitField0_ & ~0x00000040);
      containsMoreUnreadReplies_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Topic)
  }

  // @@protoc_insertion_point(class_scope:Topic)
  private static final org.matrix.dma.gchat.proto.Topic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.Topic();
  }

  public static org.matrix.dma.gchat.proto.Topic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Topic>
      PARSER = new com.google.protobuf.AbstractParser<Topic>() {
    @java.lang.Override
    public Topic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Topic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Topic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.Topic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

