// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

public interface TypingStateChangedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TypingStateChangedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .TypingState state = 1;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>optional .TypingState state = 1;</code>
   * @return The state.
   */
  org.matrix.dma.gchat.proto.TypingState getState();

  /**
   * <code>optional .UserId user_id = 2;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional .UserId user_id = 2;</code>
   * @return The userId.
   */
  org.matrix.dma.gchat.proto.UserId getUserId();
  /**
   * <code>optional .UserId user_id = 2;</code>
   */
  org.matrix.dma.gchat.proto.UserIdOrBuilder getUserIdOrBuilder();

  /**
   * <code>optional .TypingContext context = 3;</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>optional .TypingContext context = 3;</code>
   * @return The context.
   */
  org.matrix.dma.gchat.proto.TypingContext getContext();
  /**
   * <code>optional .TypingContext context = 3;</code>
   */
  org.matrix.dma.gchat.proto.TypingContextOrBuilder getContextOrBuilder();

  /**
   * <code>optional int64 start_timestamp_usec = 4;</code>
   * @return Whether the startTimestampUsec field is set.
   */
  boolean hasStartTimestampUsec();
  /**
   * <code>optional int64 start_timestamp_usec = 4;</code>
   * @return The startTimestampUsec.
   */
  long getStartTimestampUsec();
}
