// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

public interface UpdateGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RequestHeader request_header = 100;</code>
   * @return Whether the requestHeader field is set.
   */
  boolean hasRequestHeader();
  /**
   * <code>optional .RequestHeader request_header = 100;</code>
   * @return The requestHeader.
   */
  org.matrix.dma.gchat.proto.RequestHeader getRequestHeader();
  /**
   * <code>optional .RequestHeader request_header = 100;</code>
   */
  org.matrix.dma.gchat.proto.RequestHeaderOrBuilder getRequestHeaderOrBuilder();

  /**
   * <code>optional .SpaceId space_id = 1;</code>
   * @return Whether the spaceId field is set.
   */
  boolean hasSpaceId();
  /**
   * <code>optional .SpaceId space_id = 1;</code>
   * @return The spaceId.
   */
  org.matrix.dma.gchat.proto.SpaceId getSpaceId();
  /**
   * <code>optional .SpaceId space_id = 1;</code>
   */
  org.matrix.dma.gchat.proto.SpaceIdOrBuilder getSpaceIdOrBuilder();

  /**
   * <code>repeated .UpdateGroupRequest.UpdateMask update_masks = 4;</code>
   * @return A list containing the updateMasks.
   */
  java.util.List<org.matrix.dma.gchat.proto.UpdateGroupRequest.UpdateMask> getUpdateMasksList();
  /**
   * <code>repeated .UpdateGroupRequest.UpdateMask update_masks = 4;</code>
   * @return The count of updateMasks.
   */
  int getUpdateMasksCount();
  /**
   * <code>repeated .UpdateGroupRequest.UpdateMask update_masks = 4;</code>
   * @param index The index of the element to return.
   * @return The updateMasks at the given index.
   */
  org.matrix.dma.gchat.proto.UpdateGroupRequest.UpdateMask getUpdateMasks(int index);

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * optional AvatarInfo avatar_info = 6;
   * optional ?? space_details = 7;
   * </pre>
   *
   * <code>optional .GroupVisibility visibility = 5;</code>
   * @return Whether the visibility field is set.
   */
  boolean hasVisibility();
  /**
   * <pre>
   * optional AvatarInfo avatar_info = 6;
   * optional ?? space_details = 7;
   * </pre>
   *
   * <code>optional .GroupVisibility visibility = 5;</code>
   * @return The visibility.
   */
  org.matrix.dma.gchat.proto.GroupVisibility getVisibility();
  /**
   * <pre>
   * optional AvatarInfo avatar_info = 6;
   * optional ?? space_details = 7;
   * </pre>
   *
   * <code>optional .GroupVisibility visibility = 5;</code>
   */
  org.matrix.dma.gchat.proto.GroupVisibilityOrBuilder getVisibilityOrBuilder();
}
