// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

public interface UserStatusUpdatedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStatusUpdatedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .UserStatus user_status = 1;</code>
   * @return Whether the userStatus field is set.
   */
  boolean hasUserStatus();
  /**
   * <code>optional .UserStatus user_status = 1;</code>
   * @return The userStatus.
   */
  org.matrix.dma.gchat.proto.UserStatus getUserStatus();
  /**
   * <code>optional .UserStatus user_status = 1;</code>
   */
  org.matrix.dma.gchat.proto.UserStatusOrBuilder getUserStatusOrBuilder();
}
