// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google_chat.proto

package org.matrix.dma.gchat.proto;

/**
 * Protobuf type {@code WorldFilter}
 */
public final class WorldFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorldFilter)
    WorldFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorldFilter.newBuilder() to construct.
  private WorldFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorldFilter() {
    starredState_ = 0;
    visibilityState_ = 0;
    readState_ = 0;
    blockState_ = 0;
    namedState_ = 0;
    membershipState_ = 0;
    inviteCategory_ = 0;
    memberType_ = 0;
    groupType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorldFilter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_WorldFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.dma.gchat.proto.GoogleChat.internal_static_WorldFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.dma.gchat.proto.WorldFilter.class, org.matrix.dma.gchat.proto.WorldFilter.Builder.class);
  }

  /**
   * Protobuf enum {@code WorldFilter.StarredState}
   */
  public enum StarredState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STARRED_STATE_UNSPECIFIED = 0;</code>
     */
    STARRED_STATE_UNSPECIFIED(0),
    /**
     * <code>STARRED = 1;</code>
     */
    STARRED(1),
    /**
     * <code>NON_STARRED = 2;</code>
     */
    NON_STARRED(2),
    ;

    /**
     * <code>STARRED_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int STARRED_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>STARRED = 1;</code>
     */
    public static final int STARRED_VALUE = 1;
    /**
     * <code>NON_STARRED = 2;</code>
     */
    public static final int NON_STARRED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StarredState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StarredState forNumber(int value) {
      switch (value) {
        case 0: return STARRED_STATE_UNSPECIFIED;
        case 1: return STARRED;
        case 2: return NON_STARRED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StarredState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StarredState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StarredState>() {
            public StarredState findValueByNumber(int number) {
              return StarredState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(0);
    }

    private static final StarredState[] VALUES = values();

    public static StarredState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StarredState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.StarredState)
  }

  /**
   * Protobuf enum {@code WorldFilter.VisibilityState}
   */
  public enum VisibilityState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VISIBILITY_STATE_UNSPECIFIED = 0;</code>
     */
    VISIBILITY_STATE_UNSPECIFIED(0),
    /**
     * <code>VISIBLE = 1;</code>
     */
    VISIBLE(1),
    /**
     * <code>HIDDEN = 2;</code>
     */
    HIDDEN(2),
    ;

    /**
     * <code>VISIBILITY_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int VISIBILITY_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>VISIBLE = 1;</code>
     */
    public static final int VISIBLE_VALUE = 1;
    /**
     * <code>HIDDEN = 2;</code>
     */
    public static final int HIDDEN_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VisibilityState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static VisibilityState forNumber(int value) {
      switch (value) {
        case 0: return VISIBILITY_STATE_UNSPECIFIED;
        case 1: return VISIBLE;
        case 2: return HIDDEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VisibilityState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VisibilityState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VisibilityState>() {
            public VisibilityState findValueByNumber(int number) {
              return VisibilityState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(1);
    }

    private static final VisibilityState[] VALUES = values();

    public static VisibilityState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private VisibilityState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.VisibilityState)
  }

  /**
   * Protobuf enum {@code WorldFilter.ReadState}
   */
  public enum ReadState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>READ_STATE_UNSPECIFIED = 0;</code>
     */
    READ_STATE_UNSPECIFIED(0),
    /**
     * <code>READ = 1;</code>
     */
    READ(1),
    /**
     * <code>UNREAD = 2;</code>
     */
    UNREAD(2),
    /**
     * <code>UNREAD_SUBSCRIBED_TOPIC = 3;</code>
     */
    UNREAD_SUBSCRIBED_TOPIC(3),
    ;

    /**
     * <code>READ_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int READ_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>READ = 1;</code>
     */
    public static final int READ_VALUE = 1;
    /**
     * <code>UNREAD = 2;</code>
     */
    public static final int UNREAD_VALUE = 2;
    /**
     * <code>UNREAD_SUBSCRIBED_TOPIC = 3;</code>
     */
    public static final int UNREAD_SUBSCRIBED_TOPIC_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReadState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ReadState forNumber(int value) {
      switch (value) {
        case 0: return READ_STATE_UNSPECIFIED;
        case 1: return READ;
        case 2: return UNREAD;
        case 3: return UNREAD_SUBSCRIBED_TOPIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReadState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReadState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReadState>() {
            public ReadState findValueByNumber(int number) {
              return ReadState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(2);
    }

    private static final ReadState[] VALUES = values();

    public static ReadState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReadState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.ReadState)
  }

  /**
   * Protobuf enum {@code WorldFilter.BlockState}
   */
  public enum BlockState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BLOCK_STATE_UNSPECIFIED = 0;</code>
     */
    BLOCK_STATE_UNSPECIFIED(0),
    /**
     * <code>BLOCKED = 1;</code>
     */
    BLOCKED(1),
    /**
     * <code>UNBLOCKED = 2;</code>
     */
    UNBLOCKED(2),
    ;

    /**
     * <code>BLOCK_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int BLOCK_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>BLOCKED = 1;</code>
     */
    public static final int BLOCKED_VALUE = 1;
    /**
     * <code>UNBLOCKED = 2;</code>
     */
    public static final int UNBLOCKED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BlockState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BlockState forNumber(int value) {
      switch (value) {
        case 0: return BLOCK_STATE_UNSPECIFIED;
        case 1: return BLOCKED;
        case 2: return UNBLOCKED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BlockState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BlockState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BlockState>() {
            public BlockState findValueByNumber(int number) {
              return BlockState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(3);
    }

    private static final BlockState[] VALUES = values();

    public static BlockState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BlockState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.BlockState)
  }

  /**
   * Protobuf enum {@code WorldFilter.NamedState}
   */
  public enum NamedState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NAMED_STATE_UNSPECIFIED = 0;</code>
     */
    NAMED_STATE_UNSPECIFIED(0),
    /**
     * <code>NAMED = 1;</code>
     */
    NAMED(1),
    /**
     * <code>UNNAMED = 2;</code>
     */
    UNNAMED(2),
    ;

    /**
     * <code>NAMED_STATE_UNSPECIFIED = 0;</code>
     */
    public static final int NAMED_STATE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>NAMED = 1;</code>
     */
    public static final int NAMED_VALUE = 1;
    /**
     * <code>UNNAMED = 2;</code>
     */
    public static final int UNNAMED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NamedState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NamedState forNumber(int value) {
      switch (value) {
        case 0: return NAMED_STATE_UNSPECIFIED;
        case 1: return NAMED;
        case 2: return UNNAMED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NamedState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NamedState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NamedState>() {
            public NamedState findValueByNumber(int number) {
              return NamedState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(4);
    }

    private static final NamedState[] VALUES = values();

    public static NamedState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NamedState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.NamedState)
  }

  /**
   * Protobuf enum {@code WorldFilter.MemberType}
   */
  public enum MemberType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MEMBER_TYPE_UNSPECIFIED = 0;</code>
     */
    MEMBER_TYPE_UNSPECIFIED(0),
    /**
     * <code>HUMAN = 1;</code>
     */
    HUMAN(1),
    /**
     * <code>BOT = 2;</code>
     */
    BOT(2),
    ;

    /**
     * <code>MEMBER_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int MEMBER_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>HUMAN = 1;</code>
     */
    public static final int HUMAN_VALUE = 1;
    /**
     * <code>BOT = 2;</code>
     */
    public static final int BOT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MemberType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MemberType forNumber(int value) {
      switch (value) {
        case 0: return MEMBER_TYPE_UNSPECIFIED;
        case 1: return HUMAN;
        case 2: return BOT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MemberType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MemberType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MemberType>() {
            public MemberType findValueByNumber(int number) {
              return MemberType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(5);
    }

    private static final MemberType[] VALUES = values();

    public static MemberType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MemberType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.MemberType)
  }

  /**
   * Protobuf enum {@code WorldFilter.GroupType}
   */
  public enum GroupType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GROUP_TYPE_UNSPECIFIED = 0;</code>
     */
    GROUP_TYPE_UNSPECIFIED(0),
    /**
     * <code>DM = 1;</code>
     */
    DM(1),
    /**
     * <code>ROOM = 2;</code>
     */
    ROOM(2),
    ;

    /**
     * <code>GROUP_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int GROUP_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>DM = 1;</code>
     */
    public static final int DM_VALUE = 1;
    /**
     * <code>ROOM = 2;</code>
     */
    public static final int ROOM_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GroupType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GroupType forNumber(int value) {
      switch (value) {
        case 0: return GROUP_TYPE_UNSPECIFIED;
        case 1: return DM;
        case 2: return ROOM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GroupType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GroupType>() {
            public GroupType findValueByNumber(int number) {
              return GroupType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDescriptor().getEnumTypes().get(6);
    }

    private static final GroupType[] VALUES = values();

    public static GroupType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GroupType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WorldFilter.GroupType)
  }

  private int bitField0_;
  public static final int STARRED_STATE_FIELD_NUMBER = 1;
  private int starredState_ = 0;
  /**
   * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
   * @return Whether the starredState field is set.
   */
  @java.lang.Override public boolean hasStarredState() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
   * @return The starredState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.StarredState getStarredState() {
    org.matrix.dma.gchat.proto.WorldFilter.StarredState result = org.matrix.dma.gchat.proto.WorldFilter.StarredState.forNumber(starredState_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.StarredState.STARRED_STATE_UNSPECIFIED : result;
  }

  public static final int VISIBILITY_STATE_FIELD_NUMBER = 2;
  private int visibilityState_ = 0;
  /**
   * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
   * @return Whether the visibilityState field is set.
   */
  @java.lang.Override public boolean hasVisibilityState() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
   * @return The visibilityState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.VisibilityState getVisibilityState() {
    org.matrix.dma.gchat.proto.WorldFilter.VisibilityState result = org.matrix.dma.gchat.proto.WorldFilter.VisibilityState.forNumber(visibilityState_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.VisibilityState.VISIBILITY_STATE_UNSPECIFIED : result;
  }

  public static final int READ_STATE_FIELD_NUMBER = 7;
  private int readState_ = 0;
  /**
   * <code>optional .WorldFilter.ReadState read_state = 7;</code>
   * @return Whether the readState field is set.
   */
  @java.lang.Override public boolean hasReadState() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .WorldFilter.ReadState read_state = 7;</code>
   * @return The readState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.ReadState getReadState() {
    org.matrix.dma.gchat.proto.WorldFilter.ReadState result = org.matrix.dma.gchat.proto.WorldFilter.ReadState.forNumber(readState_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.ReadState.READ_STATE_UNSPECIFIED : result;
  }

  public static final int BLOCK_STATE_FIELD_NUMBER = 8;
  private int blockState_ = 0;
  /**
   * <code>optional .WorldFilter.BlockState block_state = 8;</code>
   * @return Whether the blockState field is set.
   */
  @java.lang.Override public boolean hasBlockState() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .WorldFilter.BlockState block_state = 8;</code>
   * @return The blockState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.BlockState getBlockState() {
    org.matrix.dma.gchat.proto.WorldFilter.BlockState result = org.matrix.dma.gchat.proto.WorldFilter.BlockState.forNumber(blockState_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.BlockState.BLOCK_STATE_UNSPECIFIED : result;
  }

  public static final int NAMED_STATE_FIELD_NUMBER = 9;
  private int namedState_ = 0;
  /**
   * <code>optional .WorldFilter.NamedState named_state = 9;</code>
   * @return Whether the namedState field is set.
   */
  @java.lang.Override public boolean hasNamedState() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .WorldFilter.NamedState named_state = 9;</code>
   * @return The namedState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.NamedState getNamedState() {
    org.matrix.dma.gchat.proto.WorldFilter.NamedState result = org.matrix.dma.gchat.proto.WorldFilter.NamedState.forNumber(namedState_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.NamedState.NAMED_STATE_UNSPECIFIED : result;
  }

  public static final int MEMBERSHIP_STATE_FIELD_NUMBER = 3;
  private int membershipState_ = 0;
  /**
   * <code>optional .MembershipState membership_state = 3;</code>
   * @return Whether the membershipState field is set.
   */
  @java.lang.Override public boolean hasMembershipState() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .MembershipState membership_state = 3;</code>
   * @return The membershipState.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.MembershipState getMembershipState() {
    org.matrix.dma.gchat.proto.MembershipState result = org.matrix.dma.gchat.proto.MembershipState.forNumber(membershipState_);
    return result == null ? org.matrix.dma.gchat.proto.MembershipState.MEMBER_UNKNOWN : result;
  }

  public static final int INVITE_CATEGORY_FIELD_NUMBER = 4;
  private int inviteCategory_ = 0;
  /**
   * <code>optional .InviteCategory invite_category = 4;</code>
   * @return Whether the inviteCategory field is set.
   */
  @java.lang.Override public boolean hasInviteCategory() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .InviteCategory invite_category = 4;</code>
   * @return The inviteCategory.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.InviteCategory getInviteCategory() {
    org.matrix.dma.gchat.proto.InviteCategory result = org.matrix.dma.gchat.proto.InviteCategory.forNumber(inviteCategory_);
    return result == null ? org.matrix.dma.gchat.proto.InviteCategory.UNKNOWN_INVITE : result;
  }

  public static final int MEMBER_TYPE_FIELD_NUMBER = 5;
  private int memberType_ = 0;
  /**
   * <code>optional .WorldFilter.MemberType member_type = 5;</code>
   * @return Whether the memberType field is set.
   */
  @java.lang.Override public boolean hasMemberType() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .WorldFilter.MemberType member_type = 5;</code>
   * @return The memberType.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.MemberType getMemberType() {
    org.matrix.dma.gchat.proto.WorldFilter.MemberType result = org.matrix.dma.gchat.proto.WorldFilter.MemberType.forNumber(memberType_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.MemberType.MEMBER_TYPE_UNSPECIFIED : result;
  }

  public static final int GROUP_TYPE_FIELD_NUMBER = 6;
  private int groupType_ = 0;
  /**
   * <code>optional .WorldFilter.GroupType group_type = 6;</code>
   * @return Whether the groupType field is set.
   */
  @java.lang.Override public boolean hasGroupType() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional .WorldFilter.GroupType group_type = 6;</code>
   * @return The groupType.
   */
  @java.lang.Override public org.matrix.dma.gchat.proto.WorldFilter.GroupType getGroupType() {
    org.matrix.dma.gchat.proto.WorldFilter.GroupType result = org.matrix.dma.gchat.proto.WorldFilter.GroupType.forNumber(groupType_);
    return result == null ? org.matrix.dma.gchat.proto.WorldFilter.GroupType.GROUP_TYPE_UNSPECIFIED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, starredState_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, visibilityState_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeEnum(3, membershipState_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeEnum(4, inviteCategory_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeEnum(5, memberType_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeEnum(6, groupType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(7, readState_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(8, blockState_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(9, namedState_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, starredState_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, visibilityState_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, membershipState_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, inviteCategory_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, memberType_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, groupType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, readState_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, blockState_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, namedState_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.dma.gchat.proto.WorldFilter)) {
      return super.equals(obj);
    }
    org.matrix.dma.gchat.proto.WorldFilter other = (org.matrix.dma.gchat.proto.WorldFilter) obj;

    if (hasStarredState() != other.hasStarredState()) return false;
    if (hasStarredState()) {
      if (starredState_ != other.starredState_) return false;
    }
    if (hasVisibilityState() != other.hasVisibilityState()) return false;
    if (hasVisibilityState()) {
      if (visibilityState_ != other.visibilityState_) return false;
    }
    if (hasReadState() != other.hasReadState()) return false;
    if (hasReadState()) {
      if (readState_ != other.readState_) return false;
    }
    if (hasBlockState() != other.hasBlockState()) return false;
    if (hasBlockState()) {
      if (blockState_ != other.blockState_) return false;
    }
    if (hasNamedState() != other.hasNamedState()) return false;
    if (hasNamedState()) {
      if (namedState_ != other.namedState_) return false;
    }
    if (hasMembershipState() != other.hasMembershipState()) return false;
    if (hasMembershipState()) {
      if (membershipState_ != other.membershipState_) return false;
    }
    if (hasInviteCategory() != other.hasInviteCategory()) return false;
    if (hasInviteCategory()) {
      if (inviteCategory_ != other.inviteCategory_) return false;
    }
    if (hasMemberType() != other.hasMemberType()) return false;
    if (hasMemberType()) {
      if (memberType_ != other.memberType_) return false;
    }
    if (hasGroupType() != other.hasGroupType()) return false;
    if (hasGroupType()) {
      if (groupType_ != other.groupType_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStarredState()) {
      hash = (37 * hash) + STARRED_STATE_FIELD_NUMBER;
      hash = (53 * hash) + starredState_;
    }
    if (hasVisibilityState()) {
      hash = (37 * hash) + VISIBILITY_STATE_FIELD_NUMBER;
      hash = (53 * hash) + visibilityState_;
    }
    if (hasReadState()) {
      hash = (37 * hash) + READ_STATE_FIELD_NUMBER;
      hash = (53 * hash) + readState_;
    }
    if (hasBlockState()) {
      hash = (37 * hash) + BLOCK_STATE_FIELD_NUMBER;
      hash = (53 * hash) + blockState_;
    }
    if (hasNamedState()) {
      hash = (37 * hash) + NAMED_STATE_FIELD_NUMBER;
      hash = (53 * hash) + namedState_;
    }
    if (hasMembershipState()) {
      hash = (37 * hash) + MEMBERSHIP_STATE_FIELD_NUMBER;
      hash = (53 * hash) + membershipState_;
    }
    if (hasInviteCategory()) {
      hash = (37 * hash) + INVITE_CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + inviteCategory_;
    }
    if (hasMemberType()) {
      hash = (37 * hash) + MEMBER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + memberType_;
    }
    if (hasGroupType()) {
      hash = (37 * hash) + GROUP_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + groupType_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.dma.gchat.proto.WorldFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.dma.gchat.proto.WorldFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WorldFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorldFilter)
      org.matrix.dma.gchat.proto.WorldFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_WorldFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_WorldFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.dma.gchat.proto.WorldFilter.class, org.matrix.dma.gchat.proto.WorldFilter.Builder.class);
    }

    // Construct using org.matrix.dma.gchat.proto.WorldFilter.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      starredState_ = 0;
      visibilityState_ = 0;
      readState_ = 0;
      blockState_ = 0;
      namedState_ = 0;
      membershipState_ = 0;
      inviteCategory_ = 0;
      memberType_ = 0;
      groupType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.dma.gchat.proto.GoogleChat.internal_static_WorldFilter_descriptor;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter getDefaultInstanceForType() {
      return org.matrix.dma.gchat.proto.WorldFilter.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter build() {
      org.matrix.dma.gchat.proto.WorldFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter buildPartial() {
      org.matrix.dma.gchat.proto.WorldFilter result = new org.matrix.dma.gchat.proto.WorldFilter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.dma.gchat.proto.WorldFilter result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.starredState_ = starredState_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.visibilityState_ = visibilityState_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.readState_ = readState_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.blockState_ = blockState_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.namedState_ = namedState_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.membershipState_ = membershipState_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.inviteCategory_ = inviteCategory_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.memberType_ = memberType_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.groupType_ = groupType_;
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.dma.gchat.proto.WorldFilter) {
        return mergeFrom((org.matrix.dma.gchat.proto.WorldFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.dma.gchat.proto.WorldFilter other) {
      if (other == org.matrix.dma.gchat.proto.WorldFilter.getDefaultInstance()) return this;
      if (other.hasStarredState()) {
        setStarredState(other.getStarredState());
      }
      if (other.hasVisibilityState()) {
        setVisibilityState(other.getVisibilityState());
      }
      if (other.hasReadState()) {
        setReadState(other.getReadState());
      }
      if (other.hasBlockState()) {
        setBlockState(other.getBlockState());
      }
      if (other.hasNamedState()) {
        setNamedState(other.getNamedState());
      }
      if (other.hasMembershipState()) {
        setMembershipState(other.getMembershipState());
      }
      if (other.hasInviteCategory()) {
        setInviteCategory(other.getInviteCategory());
      }
      if (other.hasMemberType()) {
        setMemberType(other.getMemberType());
      }
      if (other.hasGroupType()) {
        setGroupType(other.getGroupType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.StarredState tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.StarredState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                starredState_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            case 16: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.VisibilityState tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.VisibilityState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(2, tmpRaw);
              } else {
                visibilityState_ = tmpRaw;
                bitField0_ |= 0x00000002;
              }
              break;
            } // case 16
            case 24: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.MembershipState tmpValue =
                  org.matrix.dma.gchat.proto.MembershipState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(3, tmpRaw);
              } else {
                membershipState_ = tmpRaw;
                bitField0_ |= 0x00000020;
              }
              break;
            } // case 24
            case 32: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.InviteCategory tmpValue =
                  org.matrix.dma.gchat.proto.InviteCategory.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                inviteCategory_ = tmpRaw;
                bitField0_ |= 0x00000040;
              }
              break;
            } // case 32
            case 40: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.MemberType tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.MemberType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(5, tmpRaw);
              } else {
                memberType_ = tmpRaw;
                bitField0_ |= 0x00000080;
              }
              break;
            } // case 40
            case 48: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.GroupType tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.GroupType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(6, tmpRaw);
              } else {
                groupType_ = tmpRaw;
                bitField0_ |= 0x00000100;
              }
              break;
            } // case 48
            case 56: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.ReadState tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.ReadState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(7, tmpRaw);
              } else {
                readState_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 56
            case 64: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.BlockState tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.BlockState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(8, tmpRaw);
              } else {
                blockState_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 64
            case 72: {
              int tmpRaw = input.readEnum();
              org.matrix.dma.gchat.proto.WorldFilter.NamedState tmpValue =
                  org.matrix.dma.gchat.proto.WorldFilter.NamedState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(9, tmpRaw);
              } else {
                namedState_ = tmpRaw;
                bitField0_ |= 0x00000010;
              }
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int starredState_ = 0;
    /**
     * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
     * @return Whether the starredState field is set.
     */
    @java.lang.Override public boolean hasStarredState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
     * @return The starredState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.StarredState getStarredState() {
      org.matrix.dma.gchat.proto.WorldFilter.StarredState result = org.matrix.dma.gchat.proto.WorldFilter.StarredState.forNumber(starredState_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.StarredState.STARRED_STATE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
     * @param value The starredState to set.
     * @return This builder for chaining.
     */
    public Builder setStarredState(org.matrix.dma.gchat.proto.WorldFilter.StarredState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      starredState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.StarredState starred_state = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStarredState() {
      bitField0_ = (bitField0_ & ~0x00000001);
      starredState_ = 0;
      onChanged();
      return this;
    }

    private int visibilityState_ = 0;
    /**
     * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
     * @return Whether the visibilityState field is set.
     */
    @java.lang.Override public boolean hasVisibilityState() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
     * @return The visibilityState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.VisibilityState getVisibilityState() {
      org.matrix.dma.gchat.proto.WorldFilter.VisibilityState result = org.matrix.dma.gchat.proto.WorldFilter.VisibilityState.forNumber(visibilityState_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.VisibilityState.VISIBILITY_STATE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
     * @param value The visibilityState to set.
     * @return This builder for chaining.
     */
    public Builder setVisibilityState(org.matrix.dma.gchat.proto.WorldFilter.VisibilityState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      visibilityState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.VisibilityState visibility_state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisibilityState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      visibilityState_ = 0;
      onChanged();
      return this;
    }

    private int readState_ = 0;
    /**
     * <code>optional .WorldFilter.ReadState read_state = 7;</code>
     * @return Whether the readState field is set.
     */
    @java.lang.Override public boolean hasReadState() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .WorldFilter.ReadState read_state = 7;</code>
     * @return The readState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.ReadState getReadState() {
      org.matrix.dma.gchat.proto.WorldFilter.ReadState result = org.matrix.dma.gchat.proto.WorldFilter.ReadState.forNumber(readState_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.ReadState.READ_STATE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.ReadState read_state = 7;</code>
     * @param value The readState to set.
     * @return This builder for chaining.
     */
    public Builder setReadState(org.matrix.dma.gchat.proto.WorldFilter.ReadState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      readState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.ReadState read_state = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadState() {
      bitField0_ = (bitField0_ & ~0x00000004);
      readState_ = 0;
      onChanged();
      return this;
    }

    private int blockState_ = 0;
    /**
     * <code>optional .WorldFilter.BlockState block_state = 8;</code>
     * @return Whether the blockState field is set.
     */
    @java.lang.Override public boolean hasBlockState() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .WorldFilter.BlockState block_state = 8;</code>
     * @return The blockState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.BlockState getBlockState() {
      org.matrix.dma.gchat.proto.WorldFilter.BlockState result = org.matrix.dma.gchat.proto.WorldFilter.BlockState.forNumber(blockState_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.BlockState.BLOCK_STATE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.BlockState block_state = 8;</code>
     * @param value The blockState to set.
     * @return This builder for chaining.
     */
    public Builder setBlockState(org.matrix.dma.gchat.proto.WorldFilter.BlockState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      blockState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.BlockState block_state = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockState() {
      bitField0_ = (bitField0_ & ~0x00000008);
      blockState_ = 0;
      onChanged();
      return this;
    }

    private int namedState_ = 0;
    /**
     * <code>optional .WorldFilter.NamedState named_state = 9;</code>
     * @return Whether the namedState field is set.
     */
    @java.lang.Override public boolean hasNamedState() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .WorldFilter.NamedState named_state = 9;</code>
     * @return The namedState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.NamedState getNamedState() {
      org.matrix.dma.gchat.proto.WorldFilter.NamedState result = org.matrix.dma.gchat.proto.WorldFilter.NamedState.forNumber(namedState_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.NamedState.NAMED_STATE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.NamedState named_state = 9;</code>
     * @param value The namedState to set.
     * @return This builder for chaining.
     */
    public Builder setNamedState(org.matrix.dma.gchat.proto.WorldFilter.NamedState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      namedState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.NamedState named_state = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamedState() {
      bitField0_ = (bitField0_ & ~0x00000010);
      namedState_ = 0;
      onChanged();
      return this;
    }

    private int membershipState_ = 0;
    /**
     * <code>optional .MembershipState membership_state = 3;</code>
     * @return Whether the membershipState field is set.
     */
    @java.lang.Override public boolean hasMembershipState() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .MembershipState membership_state = 3;</code>
     * @return The membershipState.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.MembershipState getMembershipState() {
      org.matrix.dma.gchat.proto.MembershipState result = org.matrix.dma.gchat.proto.MembershipState.forNumber(membershipState_);
      return result == null ? org.matrix.dma.gchat.proto.MembershipState.MEMBER_UNKNOWN : result;
    }
    /**
     * <code>optional .MembershipState membership_state = 3;</code>
     * @param value The membershipState to set.
     * @return This builder for chaining.
     */
    public Builder setMembershipState(org.matrix.dma.gchat.proto.MembershipState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      membershipState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .MembershipState membership_state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMembershipState() {
      bitField0_ = (bitField0_ & ~0x00000020);
      membershipState_ = 0;
      onChanged();
      return this;
    }

    private int inviteCategory_ = 0;
    /**
     * <code>optional .InviteCategory invite_category = 4;</code>
     * @return Whether the inviteCategory field is set.
     */
    @java.lang.Override public boolean hasInviteCategory() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .InviteCategory invite_category = 4;</code>
     * @return The inviteCategory.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.InviteCategory getInviteCategory() {
      org.matrix.dma.gchat.proto.InviteCategory result = org.matrix.dma.gchat.proto.InviteCategory.forNumber(inviteCategory_);
      return result == null ? org.matrix.dma.gchat.proto.InviteCategory.UNKNOWN_INVITE : result;
    }
    /**
     * <code>optional .InviteCategory invite_category = 4;</code>
     * @param value The inviteCategory to set.
     * @return This builder for chaining.
     */
    public Builder setInviteCategory(org.matrix.dma.gchat.proto.InviteCategory value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      inviteCategory_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .InviteCategory invite_category = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInviteCategory() {
      bitField0_ = (bitField0_ & ~0x00000040);
      inviteCategory_ = 0;
      onChanged();
      return this;
    }

    private int memberType_ = 0;
    /**
     * <code>optional .WorldFilter.MemberType member_type = 5;</code>
     * @return Whether the memberType field is set.
     */
    @java.lang.Override public boolean hasMemberType() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .WorldFilter.MemberType member_type = 5;</code>
     * @return The memberType.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.MemberType getMemberType() {
      org.matrix.dma.gchat.proto.WorldFilter.MemberType result = org.matrix.dma.gchat.proto.WorldFilter.MemberType.forNumber(memberType_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.MemberType.MEMBER_TYPE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.MemberType member_type = 5;</code>
     * @param value The memberType to set.
     * @return This builder for chaining.
     */
    public Builder setMemberType(org.matrix.dma.gchat.proto.WorldFilter.MemberType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      memberType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.MemberType member_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      memberType_ = 0;
      onChanged();
      return this;
    }

    private int groupType_ = 0;
    /**
     * <code>optional .WorldFilter.GroupType group_type = 6;</code>
     * @return Whether the groupType field is set.
     */
    @java.lang.Override public boolean hasGroupType() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional .WorldFilter.GroupType group_type = 6;</code>
     * @return The groupType.
     */
    @java.lang.Override
    public org.matrix.dma.gchat.proto.WorldFilter.GroupType getGroupType() {
      org.matrix.dma.gchat.proto.WorldFilter.GroupType result = org.matrix.dma.gchat.proto.WorldFilter.GroupType.forNumber(groupType_);
      return result == null ? org.matrix.dma.gchat.proto.WorldFilter.GroupType.GROUP_TYPE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .WorldFilter.GroupType group_type = 6;</code>
     * @param value The groupType to set.
     * @return This builder for chaining.
     */
    public Builder setGroupType(org.matrix.dma.gchat.proto.WorldFilter.GroupType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      groupType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .WorldFilter.GroupType group_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupType() {
      bitField0_ = (bitField0_ & ~0x00000100);
      groupType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorldFilter)
  }

  // @@protoc_insertion_point(class_scope:WorldFilter)
  private static final org.matrix.dma.gchat.proto.WorldFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.dma.gchat.proto.WorldFilter();
  }

  public static org.matrix.dma.gchat.proto.WorldFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WorldFilter>
      PARSER = new com.google.protobuf.AbstractParser<WorldFilter>() {
    @java.lang.Override
    public WorldFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WorldFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorldFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.dma.gchat.proto.WorldFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

